import crypto from "node:crypto";
import { Asset, Liability, Player, Settlement, State, Trade } from "../state.js";
import { catalog, catalogById, isProperty, propertiesById } from "./catalog.js";
import { constructionLiquidation, liquidationValue, nominalAssets, investedValue } from "./bankruptcy.js";
import { calculateHousesRemaining, calculateUsedHouses, housePiecesForDevelopment, validateGameInvariants } from "./invariants.js";
import { canPayJailFine, failedJailRoll, releaseFromJail, useHabeasCorpus } from "./jail.js";
import { developmentCost, mortgageRedeemCost, organizationFee, rollDice } from "./rules.js";
import { validateTrade } from "./trading.js";

const uid=()=>crypto.randomUUID();

type MandatoryPaymentInput={debtorId:string;creditorType:"PLAYER"|"BANK";creditorPlayerId?:string;amount:number;reason:string;sourceCode:string;sourceEventId?:string};

function canonicalAsset(catalogId:string,id=uid()){
  const item=catalogById.get(catalogId);if(!item)throw Error("Patrimônio inexistente no catálogo atual.");
  const asset=new Asset();asset.id=id;asset.catalogId=item.id;asset.name=item.name;asset.kind=isProperty(item)?"property":"organization";asset.development=0;asset.mortgaged=false;asset.purchase=item.purchase;asset.mortgage=item.mortgage;asset.houseCost=isProperty(item)?item.houseCost:0;asset.condominiumCost=isProperty(item)?item.condominiumCost:0;return asset;
}
function transferAsset(from:Player,to:Player,asset:Asset){const index=from.assets.findIndex(a=>a.id===asset.id);if(index<0)throw Error("Patrimônio não encontrado.");from.assets.splice(index,1);to.assets.push(asset);}
function statsSnapshot(p:Player){return JSON.parse(JSON.stringify(p.stats));}
function restoreStats(p:Player,s:any){for(const k of ["rentPaid","rentReceived","propertiesPurchased","housesBuilt","housesSold","mortgagesCreated","tradesCompleted","turnsPlayed","jailTurns","obligationsCreated","settlementsCompleted"])(p.stats as any)[k]=Number(s?.[k]||0);}
function playerSnapshot(p:Player){return{balance:p.balance,sent:p.sent,received:p.received,bankOps:p.bankOps,habeasCorpus:p.habeasCorpus,assets:[...p.assets],stats:statsSnapshot(p)};}
function restorePlayer(p:Player,s:ReturnType<typeof playerSnapshot>){p.balance=s.balance;p.sent=s.sent;p.received=s.received;p.bankOps=s.bankOps;p.habeasCorpus=s.habeasCorpus;p.assets.clear();s.assets.forEach(a=>p.assets.push(a));restoreStats(p,s.stats);}

export class GameEngine{
  constructor(readonly state:State){}
  player(id:string){const p=this.state.players.get(id);if(!p)throw Error("Jogador inexistente.");return p;}
  assetOwnerByCatalog(catalogId:string){for(const p of this.state.players.values())if(p.assets.some(a=>a.catalogId===catalogId))return p;return undefined;}
  asset(playerId:string,assetId:string){const p=this.player(playerId),a=p.assets.find(x=>x.id===assetId);if(!a)throw Error("Patrimônio não encontrado.");return{player:p,asset:a};}
  assertInvariants(){validateGameInvariants(this.state);}
  syncHouseStock(){this.state.housesRemaining=calculateHousesRemaining(this.state);}
  ensureActive(p:Player){if(p.bankrupt||p.spectator)throw Error("Jogador falido/espectador não pode realizar esta ação.");}
  ensureTurn(playerId:string){if(this.state.gameStarted&&this.state.currentPlayerId&&this.state.currentPlayerId!==playerId)throw Error("Esta ação só pode ser realizada na sua vez.");}
  ensureNoRequiredAction(playerId:string){if(this.state.requiredAction&&this.state.requiredActionPlayerId===playerId)throw Error(`Resolva a ação obrigatória antes de continuar: ${this.state.requiredAction}.`);}

  purchaseAsset(playerId:string,catalogId:string){const p=this.player(playerId);this.ensureActive(p);this.ensureTurn(playerId);this.ensureNoRequiredAction(playerId);const item=catalogById.get(catalogId);if(!item)throw Error("Patrimônio inexistente no catálogo oficial.");if(this.assetOwnerByCatalog(catalogId))throw Error("Patrimônio já possui proprietário.");if(p.balance<item.purchase)throw Error("Saldo insuficiente.");const a=canonicalAsset(catalogId);p.balance-=item.purchase;p.bankOps++;p.assets.push(a);p.stats.propertiesPurchased++;this.assertInvariants();return a;}

  private developmentPlan(playerId:string,assetId:string,target:number){
    const {player:p,asset:a}=this.asset(playerId,assetId);this.ensureActive(p);this.ensureTurn(playerId);this.ensureNoRequiredAction(playerId);if(a.kind!=="property")throw Error("Somente propriedades aceitam construções.");if(a.mortgaged)throw Error("Não é possível construir em propriedade hipotecada.");if(!Number.isInteger(target)||target<0||target>5)throw Error("Nível de construção inválido.");const property=propertiesById.get(a.catalogId);if(!property)throw Error("Propriedade fora do catálogo canônico.");const group=[...propertiesById.values()].filter(x=>x.group===property.group);const owned=group.map(x=>p.assets.find(v=>v.catalogId===x.id)).filter(Boolean) as Asset[];if(this.state.rules.requireFullGroupForBuilding&&owned.length!==group.length)throw Error("É necessário possuir todas as propriedades do grupo para construir.");if(this.state.rules.requireFullGroupForBuilding&&owned.some(x=>x.mortgaged))throw Error("Não é possível construir enquanto houver propriedade hipotecada no grupo.");const beforeCondo=this.state.rules.housesBeforeCondo;if(beforeCondo===3&&target===4)throw Error("Nesta partida o condomínio substitui a quarta casa: evolua de 3 casas diretamente para condomínio.");const validTransition=(target===5&&a.development===beforeCondo)||(a.development===5&&target===beforeCondo)||Math.abs(target-a.development)===1;if(!validTransition)throw Error("Altere apenas um nível permitido por operação.");if(this.state.rules.requireEvenBuilding&&target===5&&owned.some(x=>x.id!==a.id&&x.development<beforeCondo))throw Error(`As propriedades consideradas pela regra de uniformidade precisam ter ${beforeCondo} casas antes do condomínio.`);if(this.state.rules.requireEvenBuilding&&target<5){const levels=owned.map(x=>x.development===5?beforeCondo:x.development),idx=owned.findIndex(x=>x.id===a.id),next=[...levels];next[idx]=target;if(next.length&&Math.max(...next)-Math.min(...next)>1)throw Error("As construções do grupo devem permanecer distribuídas uniformemente.");}const cost=developmentCost(property,a.development,target,beforeCondo),beforePieces=housePiecesForDevelopment(a.development,beforeCondo),afterPieces=housePiecesForDevelopment(target,beforeCondo),delta=afterPieces-beforePieces;if(this.state.rules.limitedHouseStock&&delta>0&&this.state.housesRemaining<delta)throw Error("Não há casas suficientes no banco.");return{p,a,property,cost,delta,target};
  }
  changeDevelopment(playerId:string,assetId:string,target:number){const plan=this.developmentPlan(playerId,assetId,target),beforeStock=this.state.housesRemaining;if(plan.cost>0&&plan.p.balance<plan.cost)throw Error("Saldo insuficiente.");plan.p.balance-=plan.cost;plan.a.development=target;if(plan.delta>0)plan.p.stats.housesBuilt+=plan.delta;else if(plan.delta<0)plan.p.stats.housesSold+=Math.abs(plan.delta);this.syncHouseStock();if(this.state.rules.limitedHouseStock&&beforeStock===0&&this.state.housesRemaining>0)this.state.houseAuctionAvailable=true;this.assertInvariants();return{cost:plan.cost,delta:plan.delta,asset:plan.a};}

  private assetCommitted(assetId:string,catalogId:string,options:{ignorePendingId?:string;ignoreTradeId?:string;ignoreSettlementId?:string}={}){for(const q of this.state.pending.values())if(q.id!==options.ignorePendingId&&q.catalogId===catalogId&&(q.kind==="asset"||q.kind==="bank_sale"))return "Este título já está envolvido em uma solicitação pendente.";for(const t of this.state.trades.values())if(t.id!==options.ignoreTradeId&&([...t.proposerAssetIds].includes(assetId)||[...t.recipientAssetIds].includes(assetId)))return "Este título já está envolvido em uma negociação.";for(const settlement of this.state.settlements.values())if(settlement.id!==options.ignoreSettlementId&&[...settlement.assetIds].includes(assetId))return "Este título já está envolvido em um acordo de dívida.";return "";}
  validateAssetDisposition(playerId:string,assetId:string,options:{ignorePendingId?:string;ignoreTradeId?:string;ignoreSettlementId?:string}={}){const {player:p,asset:a}=this.asset(playerId,assetId);this.ensureActive(p);if(a.development>0)throw Error("Venda as construções antes de negociar este título.");if(a.mortgaged)throw Error("Resgate a hipoteca antes de transferir ou vender este título.");const item=catalogById.get(a.catalogId);if(!item)throw Error("Patrimônio fora do catálogo canônico.");const committed=this.assetCommitted(a.id,a.catalogId,options);if(committed)throw Error(committed);if(isProperty(item)&&this.state.rules.requireFullGroupForBuilding){const property=propertiesById.get(a.catalogId),group=property?[...propertiesById.values()].filter(x=>x.group===property.group):[];const hasGroupDevelopment=group.some(x=>x.id!==a.catalogId&&p.assets.some(owned=>owned.catalogId===x.id&&owned.development>0));if(hasGroupDevelopment)throw Error("Venda as construções do grupo antes de negociar este título.");}return{player:p,asset:a,item};}
  private executeAssetSaleToBank(playerId:string,assetId:string,options:{ignorePendingId?:string}={}){const {player:p,asset:a,item}=this.validateAssetDisposition(playerId,assetId,{ignorePendingId:options.ignorePendingId});const index=p.assets.findIndex(x=>x.id===a.id);if(index<0)throw Error("Patrimônio não encontrado.");p.assets.splice(index,1);p.balance+=item.purchase;p.received+=item.purchase;p.bankOps++;this.syncHouseStock();this.assertInvariants();return item.purchase;}
  sellAssetToBank(playerId:string,assetId:string,liabilityId:string){const p=this.player(playerId);this.ensureActive(p);this.ensureTurn(playerId);const liability=this.state.liabilities.get(liabilityId);if(!liability||liability.debtorId!==p.id||liability.status!=="open")throw Error("Venda ao banco exige uma dívida aberta selecionada explicitamente.");return this.executeAssetSaleToBank(playerId,assetId);}
  sellAssetToBankVoluntary(playerId:string,assetId:string,pendingId:string){const p=this.player(playerId);this.ensureActive(p);return this.executeAssetSaleToBank(playerId,assetId,{ignorePendingId:pendingId});}
  mortgage(playerId:string,assetId:string){const {player:p,asset:a}=this.asset(playerId,assetId);this.ensureActive(p);this.ensureTurn(playerId);this.ensureNoRequiredAction(playerId);if(a.mortgaged)throw Error("Patrimônio já hipotecado.");if(a.development>0)throw Error("Venda todas as construções antes de hipotecar.");const item=catalogById.get(a.catalogId)!;a.mortgaged=true;p.balance+=item.mortgage;p.stats.mortgagesCreated++;this.assertInvariants();return item.mortgage;}
  redeemMortgage(playerId:string,assetId:string){const {player:p,asset:a}=this.asset(playerId,assetId);this.ensureActive(p);this.ensureTurn(playerId);this.ensureNoRequiredAction(playerId);if(!a.mortgaged)throw Error("Patrimônio não está hipotecado.");const item=catalogById.get(a.catalogId)!;const cost=mortgageRedeemCost(item.mortgage,this.state.rules.mortgageRedemptionInterest);if(p.balance<cost)throw Error("Saldo insuficiente para resgatar a hipoteca.");p.balance-=cost;a.mortgaged=false;this.assertInvariants();return cost;}

  organizationFee(catalogId:string,diceSum:number){const owner=this.assetOwnerByCatalog(catalogId);const item=catalogById.get(catalogId);if(!item||isProperty(item))throw Error("Instituição inválida.");if(!owner)return{amount:0,ownerId:"",ownsAll:false};const asset=owner.assets.find(a=>a.catalogId===catalogId)!;if(asset.mortgaged)return{amount:0,ownerId:owner.id,ownsAll:false};const ownsAll=catalog.organizations.every(o=>owner.assets.some(a=>a.catalogId===o.id));return{amount:organizationFee(diceSum,item.multiplier,ownsAll),ownerId:owner.id,ownsAll};}
  resolveRent(playerId:string,catalogId:string){const debtor=this.player(playerId);this.ensureActive(debtor);const item=catalogById.get(catalogId);if(!item||!isProperty(item))throw Error("Propriedade inválida.");const owner=this.assetOwnerByCatalog(catalogId);if(!owner)return{status:"none",reason:"UNOWNED",amount:0,ownerId:""};if(owner.id===debtor.id)return{status:"none",reason:"SELF_OWNED",amount:0,ownerId:owner.id};const asset=owner.assets.find(a=>a.catalogId===catalogId)!;if(asset.mortgaged)return{status:"none",reason:"MORTGAGED",amount:0,ownerId:owner.id};const amount=item.rent[asset.development];const payment=this.resolveMandatoryPayment({debtorId:debtor.id,creditorType:"PLAYER",creditorPlayerId:owner.id,amount,reason:`Aluguel de ${item.name}`,sourceCode:"RENT"});return{...payment,amount,ownerId:owner.id,catalogId};}
  resolveInstitution(playerId:string,catalogId:string,diceSum:number){const debtor=this.player(playerId);this.ensureActive(debtor);const item=catalogById.get(catalogId);if(!item||isProperty(item))throw Error("Instituição inválida.");const owner=this.assetOwnerByCatalog(catalogId);if(!owner)return{status:"none",reason:"UNOWNED",amount:0,ownerId:""};if(owner.id===debtor.id)return{status:"none",reason:"SELF_OWNED",amount:0,ownerId:owner.id};const asset=owner.assets.find(a=>a.catalogId===catalogId)!;if(asset.mortgaged)return{status:"none",reason:"MORTGAGED",amount:0,ownerId:owner.id};const ownsAll=catalog.organizations.every(o=>owner.assets.some(a=>a.catalogId===o.id));const amount=organizationFee(diceSum,item.multiplier,ownsAll);const payment=this.resolveMandatoryPayment({debtorId:debtor.id,creditorType:"PLAYER",creditorPlayerId:owner.id,amount,reason:`Taxa de ${item.name}`,sourceCode:"ORGANIZATION"});return{...payment,amount,ownerId:owner.id,ownsAll,catalogId};}

  private applyPaymentStats(sourceCode:string,debtor:Player,creditor:Player|undefined,amount:number){if(sourceCode==="RENT"&&creditor){debtor.stats.rentPaid+=amount;creditor.stats.rentReceived+=amount;}}
  resolveMandatoryPayment(input:MandatoryPaymentInput){const debtor=this.player(input.debtorId);this.ensureActive(debtor);if(!Number.isFinite(input.amount)||input.amount<=0)throw Error("Pagamento obrigatório inválido.");let creditor:Player|undefined;if(input.creditorType==="PLAYER"){if(!input.creditorPlayerId||input.creditorPlayerId===debtor.id)throw Error("Credor inválido.");creditor=this.player(input.creditorPlayerId);this.ensureActive(creditor);}const amount=Math.round(input.amount);if(debtor.balance<amount){const existing=[...this.state.liabilities.values()].find(l=>l.debtorId===debtor.id&&l.status==="open"&&l.sourceCode===input.sourceCode&&l.creditorType===input.creditorType&&l.creditorPlayerId===(input.creditorPlayerId||"")&&l.amount===amount);const liability=existing||this.createLiability({...input,amount});return{status:"liability" as const,paid:0,liabilityId:liability.id,shortfall:Math.max(0,amount-debtor.balance)};}debtor.balance-=amount;if(creditor){creditor.balance+=amount;debtor.sent+=amount;creditor.received+=amount;}else debtor.bankOps++;this.applyPaymentStats(input.sourceCode,debtor,creditor,amount);this.assertInvariants();return{status:"paid" as const,paid:amount,liabilityId:"",shortfall:0};}
  createLiability(input:{debtorId:string;creditorType:"PLAYER"|"BANK";creditorPlayerId?:string;amount:number;reason:string;sourceCode?:string;sourceEventId?:string}){const debtor=this.player(input.debtorId);this.ensureActive(debtor);if(!Number.isFinite(input.amount)||input.amount<=0)throw Error("Obrigação inválida.");if(input.creditorType==="PLAYER"){if(!input.creditorPlayerId||input.creditorPlayerId===debtor.id)throw Error("Credor inválido.");this.player(input.creditorPlayerId);}const liability=new Liability();liability.id=uid();liability.debtorId=debtor.id;liability.creditorType=input.creditorType;liability.creditorPlayerId=input.creditorPlayerId||"";liability.amount=Math.round(input.amount);liability.remaining=liability.amount;liability.reason=input.reason;liability.sourceCode=input.sourceCode||"MANUAL";liability.sourceEventId=input.sourceEventId||"";liability.createdAt=Date.now();this.state.liabilities.set(liability.id,liability);debtor.stats.obligationsCreated++;this.assertInvariants();return liability;}
  payLiability(playerId:string,liabilityId:string,amount?:number){const liability=this.state.liabilities.get(liabilityId);if(!liability||liability.debtorId!==playerId||liability.status!=="open")throw Error("Obrigação inexistente.");const debtor=this.player(playerId);const pay=Math.min(liability.remaining,amount===undefined?debtor.balance:Math.max(0,Math.round(amount)));if(pay<=0||debtor.balance<pay)throw Error("Saldo insuficiente.");let creditor:Player|undefined;debtor.balance-=pay;if(liability.creditorType==="PLAYER"){creditor=this.player(liability.creditorPlayerId);creditor.balance+=pay;debtor.sent+=pay;creditor.received+=pay;}else debtor.bankOps++;this.applyPaymentStats(liability.sourceCode,debtor,creditor,pay);liability.remaining-=pay;if(liability.remaining===0){liability.status="paid";if(liability.sourceCode==="JAIL_FINE"&&debtor.jailed){releaseFromJail(debtor);if(this.state.requiredLiabilityId===liability.id)this.clearRequiredAction();}}this.assertInvariants();return pay;}

  proposeTrade(input:{proposerId:string;recipientId:string;proposerCash:number;recipientCash:number;proposerAssetIds:string[];recipientAssetIds:string[];proposerHabeasCount?:number;recipientHabeasCount?:number}){const proposer=this.player(input.proposerId),recipient=this.player(input.recipientId);this.ensureActive(proposer);this.ensureActive(recipient);if(proposer.id===recipient.id)throw Error("Escolha outro jogador.");const pAssets=input.proposerAssetIds.map(id=>proposer.assets.find(a=>a.id===id)).filter(Boolean) as Asset[],rAssets=input.recipientAssetIds.map(id=>recipient.assets.find(a=>a.id===id)).filter(Boolean) as Asset[];if(pAssets.length!==input.proposerAssetIds.length||rAssets.length!==input.recipientAssetIds.length)throw Error("Patrimônio da negociação não encontrado.");for(const a of pAssets)this.validateAssetDisposition(proposer.id,a.id);for(const a of rAssets)this.validateAssetDisposition(recipient.id,a.id);validateTrade([proposer,recipient],[...pAssets,...rAssets]);const ph=Math.max(0,Math.round(input.proposerHabeasCount||0)),rh=Math.max(0,Math.round(input.recipientHabeasCount||0));if(input.proposerCash<0||input.recipientCash<0||proposer.balance<input.proposerCash||recipient.balance<input.recipientCash)throw Error("Saldo insuficiente para esta negociação.");if(proposer.habeasCorpus<ph||recipient.habeasCorpus<rh)throw Error("Habeas Corpus indisponível para negociação.");if(!pAssets.length&&!rAssets.length&&!input.proposerCash&&!input.recipientCash&&!ph&&!rh)throw Error("Negociação vazia.");const trade=new Trade();trade.id=uid();trade.proposerId=proposer.id;trade.recipientId=recipient.id;trade.proposerCash=Math.round(input.proposerCash);trade.recipientCash=Math.round(input.recipientCash);trade.proposerHabeasCount=ph;trade.recipientHabeasCount=rh;trade.createdAt=Date.now();trade.revision=this.state.revision;input.proposerAssetIds.forEach(id=>trade.proposerAssetIds.push(id));input.recipientAssetIds.forEach(id=>trade.recipientAssetIds.push(id));this.state.trades.set(trade.id,trade);this.assertInvariants();return trade;}
  respondTrade(playerId:string,tradeId:string,accept:boolean){const trade=this.state.trades.get(tradeId);if(!trade||trade.status!=="pending")throw Error("Negociação inexistente ou encerrada.");if(trade.recipientId!==playerId)throw Error("Somente o destinatário pode responder esta negociação.");if(!accept){this.state.trades.delete(trade.id);return{accepted:false};}const proposer=this.player(trade.proposerId),recipient=this.player(trade.recipientId);validateTrade([proposer,recipient],[]);const pa=[...trade.proposerAssetIds].map(id=>proposer.assets.find(a=>a.id===id)),ra=[...trade.recipientAssetIds].map(id=>recipient.assets.find(a=>a.id===id));if(pa.some(a=>!a)||ra.some(a=>!a))throw Error("A negociação mudou: patrimônio não pertence mais ao ofertante correto.");for(const a of pa as Asset[])this.validateAssetDisposition(proposer.id,a.id,{ignoreTradeId:trade.id});for(const a of ra as Asset[])this.validateAssetDisposition(recipient.id,a.id,{ignoreTradeId:trade.id});validateTrade([proposer,recipient],[...(pa as Asset[]),...(ra as Asset[])]);if(proposer.balance<trade.proposerCash||recipient.balance<trade.recipientCash)throw Error("A negociação mudou: saldo insuficiente.");if(proposer.habeasCorpus<trade.proposerHabeasCount||recipient.habeasCorpus<trade.recipientHabeasCount)throw Error("A negociação mudou: Habeas Corpus indisponível.");const ps=playerSnapshot(proposer),rs=playerSnapshot(recipient),status=trade.status;try{proposer.balance=proposer.balance-trade.proposerCash+trade.recipientCash;recipient.balance=recipient.balance-trade.recipientCash+trade.proposerCash;proposer.habeasCorpus=proposer.habeasCorpus-trade.proposerHabeasCount+trade.recipientHabeasCount;recipient.habeasCorpus=recipient.habeasCorpus-trade.recipientHabeasCount+trade.proposerHabeasCount;for(const a of pa as Asset[])transferAsset(proposer,recipient,a);for(const a of ra as Asset[])transferAsset(recipient,proposer,a);proposer.stats.tradesCompleted++;recipient.stats.tradesCompleted++;trade.status="accepted";this.state.trades.delete(trade.id);this.assertInvariants();return{accepted:true,proposer,recipient};}catch(error){restorePlayer(proposer,ps);restorePlayer(recipient,rs);trade.status=status;this.state.trades.set(trade.id,trade);throw error;}}
  cancelTrade(playerId:string,tradeId:string){const trade=this.state.trades.get(tradeId);if(!trade||trade.proposerId!==playerId)throw Error("Somente o proponente pode cancelar.");this.state.trades.delete(trade.id);return true;}

  proposeSettlement(input:{debtorId:string;liabilityId:string;cash:number;assetIds:string[];note:string}){const l=this.state.liabilities.get(input.liabilityId);if(!l||l.debtorId!==input.debtorId||l.status!=="open"||l.creditorType!=="PLAYER")throw Error("Settlement exige obrigação aberta entre jogadores.");const debtor=this.player(input.debtorId),creditor=this.player(l.creditorPlayerId);validateTrade([debtor,creditor],[]);const assets=input.assetIds.map(id=>debtor.assets.find(a=>a.id===id));if(assets.some(a=>!a))throw Error("Patrimônio do acordo inexistente.");for(const a of assets as Asset[])this.validateAssetDisposition(debtor.id,a.id);validateTrade([debtor,creditor],assets as Asset[]);if(input.cash<0||debtor.balance<input.cash)throw Error("Dinheiro indisponível.");if(input.cash<=0&&!input.assetIds.length)throw Error("Settlement vazio.");const s=new Settlement();s.id=uid();s.liabilityId=l.id;s.debtorId=debtor.id;s.creditorPlayerId=creditor.id;s.cash=Math.round(input.cash);s.note=input.note;s.createdAt=Date.now();input.assetIds.forEach(id=>s.assetIds.push(id));this.state.settlements.set(s.id,s);this.assertInvariants();return s;}
  respondSettlement(playerId:string,id:string,accept:boolean){const s=this.state.settlements.get(id);if(!s||s.creditorPlayerId!==playerId||s.status!=="pending")throw Error("Settlement inválido.");if(!accept){this.state.settlements.delete(id);return false;}const l=this.state.liabilities.get(s.liabilityId);if(!l||l.status!=="open")throw Error("A obrigação foi alterada.");const debtor=this.player(s.debtorId),creditor=this.player(playerId);validateTrade([debtor,creditor],[]);if(debtor.balance<s.cash)throw Error("Saldo alterado.");const assets=[...s.assetIds].map(id=>debtor.assets.find(a=>a.id===id));if(assets.some(a=>!a))throw Error("Patrimônio alterado.");for(const a of assets as Asset[])this.validateAssetDisposition(debtor.id,a.id,{ignoreSettlementId:s.id});validateTrade([debtor,creditor],assets as Asset[]);const ds=playerSnapshot(debtor),cs=playerSnapshot(creditor),oldRemaining=l.remaining,oldStatus=l.status;try{debtor.balance-=s.cash;creditor.balance+=s.cash;debtor.sent+=s.cash;creditor.received+=s.cash;for(const a of assets as Asset[])transferAsset(debtor,creditor,a);l.status="settled";l.remaining=0;debtor.stats.settlementsCompleted++;creditor.stats.settlementsCompleted++;this.state.settlements.delete(id);this.assertInvariants();return true;}catch(error){restorePlayer(debtor,ds);restorePlayer(creditor,cs);l.remaining=oldRemaining;l.status=oldStatus;this.state.settlements.set(id,s);throw error;}}

  liquidity(playerId:string,liabilityId:string){const p=this.player(playerId),l=this.state.liabilities.get(liabilityId);if(!l||l.debtorId!==p.id||l.status!=="open")throw Error("Obrigação inválida.");return{liabilityId:l.id,amount:l.remaining,balance:p.balance,shortfall:Math.max(0,l.remaining-p.balance),developed:[...p.assets].filter(a=>a.development>0).map(a=>a.id),mortgageable:[...p.assets].filter(a=>!a.mortgaged&&a.development===0).map(a=>a.id),sellable:[...p.assets].filter(a=>!a.mortgaged&&a.development===0).map(a=>a.id),canDeclareBankruptcy:p.balance<l.remaining&&![...p.assets].some(a=>a.development>0||(!a.mortgaged&&a.development===0))};}
  declareBankruptcy(playerId:string,liabilityId:string){const p=this.player(playerId),open=[...this.state.liabilities.values()].filter(x=>x.debtorId===p.id&&x.status==="open");if(open.length!==1)throw Error(open.length>1?"Existem múltiplas obrigações abertas. Resolva ou consolide as obrigações antes da falência.":"Falência exige uma obrigação aberta.");const l=open[0];if(l.id!==liabilityId)throw Error("Selecione explicitamente a obrigação que motivará a falência.");if(p.bankrupt)throw Error("Jogador já falido.");const liquid=this.liquidity(p.id,l.id);if(!liquid.canDeclareBankruptcy)throw Error("Ainda existem opções de liquidez antes da falência.");const snapshot={balance:p.balance,bankOps:p.bankOps,sent:p.sent,received:p.received,stats:statsSnapshot(p),assets:[...p.assets].map(a=>({id:a.id,catalogId:a.catalogId,development:a.development,mortgaged:a.mortgaged})),liabilities:open.map(x=>JSON.parse(JSON.stringify(x))),payments:[] as any[]};let constructionRefund=0,propertyRefund=0;for(const a of p.assets){constructionRefund+=constructionLiquidation(a,this.state.rules.housesBeforeCondo);if(!a.mortgaged)propertyRefund+=a.purchase;}p.balance+=constructionRefund+propertyRefund;const paid=Math.min(p.balance,l.remaining);p.balance-=paid;if(l.creditorType==="PLAYER"){const creditor=this.player(l.creditorPlayerId);creditor.balance+=paid;creditor.received+=paid;p.sent+=paid;snapshot.payments.push({playerId:creditor.id,amount:paid});}else p.bankOps++;const loss=l.remaining-paid;l.remaining=0;l.status="bankrupt";p.assets.clear();this.syncHouseStock();p.bankrupt=true;p.spectator=true;p.jailed=false;p.jailVisiting=false;p.startBonusAvailable=false;for(const [id,t] of this.state.trades)if(t.proposerId===p.id||t.recipientId===p.id)this.state.trades.delete(id);for(const [id,s] of this.state.settlements)if(s.debtorId===p.id||s.creditorPlayerId===p.id)this.state.settlements.delete(id);for(const [id,r] of this.state.pending)if(r.fromId===p.id||r.toId===p.id)this.state.pending.delete(id);p.bankruptcyBackup=JSON.stringify(snapshot);this.evaluateVictory();this.assertInvariants();return{paid,loss,constructionRefund,propertyRefund};}
  restoreBankruptcy(playerId:string){const p=this.player(playerId);if(!p.bankrupt||!p.bankruptcyBackup)throw Error("Não há falência reversível para este jogador.");const snapshot=JSON.parse(p.bankruptcyBackup);for(const raw of snapshot.assets||[]){if(!catalogById.has(raw.catalogId))throw Error(`Patrimônio desconhecido no catálogo atual: ${raw.catalogId}.`);const owner=this.assetOwnerByCatalog(raw.catalogId);if(owner&&owner.id!==p.id)throw Error("Não é possível restaurar: patrimônio já possui novo proprietário.");}const restorePieces=(snapshot.assets||[]).reduce((sum:number,a:any)=>sum+housePiecesForDevelopment(Number(a.development)||0,this.state.rules.housesBeforeCondo),0);if(this.state.rules.limitedHouseStock&&calculateUsedHouses(this.state)+restorePieces>80)throw Error("Não há peças suficientes para restaurar a falência sem criar estado impossível.");for(const pay of snapshot.payments||[]){const other=this.player(pay.playerId);if(other.balance<pay.amount)throw Error("Não é possível desfazer: o pagamento ao credor já não pode ser revertido com segurança.");}for(const pay of snapshot.payments||[])this.player(pay.playerId).balance-=pay.amount;p.balance=Number(snapshot.balance);p.bankOps=Number(snapshot.bankOps);p.sent=Number(snapshot.sent);p.received=Number(snapshot.received);restoreStats(p,snapshot.stats||{});p.assets.clear();for(const raw of snapshot.assets||[]){const a=canonicalAsset(raw.catalogId,raw.id);a.development=Number(raw.development);a.mortgaged=Boolean(raw.mortgaged);p.assets.push(a);}for(const [id,x] of [...this.state.liabilities])if(x.debtorId===p.id)this.state.liabilities.delete(id);for(const raw of snapshot.liabilities||[]){const x=new Liability();Object.assign(x,raw);this.state.liabilities.set(x.id,x);}p.bankrupt=false;p.spectator=false;p.bankruptcyBackup="";if(this.state.winnerId){this.state.winnerId="";this.state.gamePhase="ASSISTED_TURN";this.state.gameFinishedAt=0;}this.syncHouseStock();this.assertInvariants();return true;}

  startTurnTracker(order:string[]){if(this.state.gameStarted)throw Error("O rastreador de turnos já foi iniciado.");const unique=[...new Set(order)];if(unique.length<2||unique.some(id=>!this.state.players.has(id)))throw Error("Ordem de turnos inválida.");this.state.turnOrder.clear();unique.forEach(id=>this.state.turnOrder.push(id));this.state.currentPlayerId=unique[0];this.state.round=1;this.state.turnNumber=1;this.state.gameStarted=true;this.state.rulesLocked=true;this.state.gamePhase="ASSISTED_TURN";if(this.state.rules.timedGame){this.state.startedAt=Date.now();this.state.durationMs=this.state.rules.timeLimitMs;this.state.totalPausedMs=0;this.state.pausedAt=0;}this.assertInvariants();return unique[0];}
  endTurn(playerId:string){this.ensureTurn(playerId);if(this.state.requiredAction&&this.state.requiredActionPlayerId===playerId)throw Error(`Resolva ${this.state.requiredAction} antes de encerrar o turno.`);const p=this.player(playerId);p.startBonusAvailable=false;p.stats.turnsPlayed++;const doubles=this.state.rules.useDigitalDice&&this.state.die1>0&&this.state.die1===this.state.die2&&!p.jailed;if(doubles){this.state.die1=0;this.state.die2=0;return playerId;}const order=[...this.state.turnOrder].filter(id=>this.state.players.has(id)&&!this.player(id).bankrupt);if(!order.length)throw Error("Não há jogadores elegíveis.");const index=order.indexOf(playerId),next=order[(index+1)%order.length];if(index===order.length-1)this.state.round++;this.state.turnNumber++;this.state.currentPlayerId=next;this.state.die1=0;this.state.die2=0;this.state.consecutiveDoubles=0;return next;}
  rollAssistiveDice(playerId:string,randomInt:typeof crypto.randomInt=crypto.randomInt){if(!this.state.rules.useDigitalDice)throw Error("Dados digitais não estão habilitados nesta sala.");this.ensureTurn(playerId);const p=this.player(playerId);this.ensureActive(p);this.ensureNoRequiredAction(playerId);const dice=rollDice(randomInt);this.state.die1=dice.first;this.state.die2=dice.second;if(p.jailed){if(dice.doubles){releaseFromJail(p);this.state.consecutiveDoubles=0;return{...dice,releasedFromJail:true,sentToJail:false,extraTurn:false};}const third=this.failedJailAttempt(playerId);return{...dice,releasedFromJail:false,sentToJail:false,thirdAttempt:third,extraTurn:false};}this.state.consecutiveDoubles=dice.doubles?this.state.consecutiveDoubles+1:0;if(this.state.consecutiveDoubles>=3){this.sendToJail(playerId);this.state.consecutiveDoubles=0;return{...dice,releasedFromJail:false,sentToJail:true,extraTurn:false};}return{...dice,releasedFromJail:false,sentToJail:false,extraTurn:dice.doubles};}
  markStartBonusAvailable(playerId:string){const p=this.player(playerId);this.ensureActive(p);if(!this.state.gameStarted)throw Error("Inicie o rastreador de turnos antes de registrar pró-labore.");if(this.state.currentPlayerId!==playerId)throw Error("Pró-labore só pode ser marcado para o jogador atual.");if(p.startBonusAvailable)throw Error("Pró-labore já está disponível nesta jogada.");if(this.state.rules.autoCollectStart){p.balance+=this.state.rules.startSalary;p.bankOps++;return{auto:true,amount:this.state.rules.startSalary};}p.startBonusAvailable=true;return{auto:false,amount:this.state.rules.startSalary};}
  claimStartBonus(playerId:string){const p=this.player(playerId);this.ensureActive(p);this.ensureTurn(playerId);if(!p.startBonusAvailable)throw Error("Nenhum pró-labore está pendente nesta jogada.");p.startBonusAvailable=false;p.balance+=this.state.rules.startSalary;p.bankOps++;return this.state.rules.startSalary;}

  private clearRequiredAction(){this.state.requiredAction="";this.state.requiredActionPlayerId="";this.state.requiredLiabilityId="";}
  sendToJail(playerId:string){const p=this.player(playerId);p.jailed=true;p.jailVisiting=false;p.jailAttempts=0;p.startBonusAvailable=false;if(this.state.requiredActionPlayerId===playerId)this.clearRequiredAction();return p;}
  markJailVisit(playerId:string){const p=this.player(playerId);p.jailed=false;p.jailVisiting=true;p.jailAttempts=0;if(this.state.requiredActionPlayerId===playerId)this.clearRequiredAction();return p;}
  failedJailAttempt(playerId:string){const p=this.player(playerId);this.ensureTurn(playerId);const third=failedJailRoll(p);p.stats.jailTurns++;if(third){this.state.requiredAction="PAY_JAIL_FINE";this.state.requiredActionPlayerId=playerId;this.state.requiredLiabilityId="";}return third;}
  payJailFine(playerId:string){const p=this.player(playerId);this.ensureTurn(playerId);canPayJailFine(p,this.state.rules.allowEarlyJailFine);if(this.state.requiredLiabilityId){const existing=this.state.liabilities.get(this.state.requiredLiabilityId);if(existing&&existing.status==="open")return{status:"liability" as const,paid:0,liabilityId:existing.id,shortfall:Math.max(0,existing.remaining-p.balance)};}const result=this.resolveMandatoryPayment({debtorId:p.id,creditorType:"BANK",amount:this.state.rules.jailFine,reason:"Fiança obrigatória da cadeia",sourceCode:"JAIL_FINE"});if(result.status==="paid"){releaseFromJail(p);this.clearRequiredAction();}else{this.state.requiredAction="PAY_JAIL_FINE";this.state.requiredActionPlayerId=p.id;this.state.requiredLiabilityId=result.liabilityId;}return result;}
  useHabeas(playerId:string){const p=this.player(playerId);this.ensureTurn(playerId);useHabeasCorpus(p);if(this.state.requiredLiabilityId){const l=this.state.liabilities.get(this.state.requiredLiabilityId);if(l&&l.debtorId===p.id&&l.sourceCode==="JAIL_FINE"&&l.status==="open"){l.status="cancelled";l.remaining=0;}}if(this.state.requiredActionPlayerId===p.id)this.clearRequiredAction();return true;}
  grantHabeas(playerId:string){const p=this.player(playerId);this.ensureActive(p);p.habeasCorpus++;this.assertInvariants();return p.habeasCorpus;}

  assignInitialAsset(playerId:string,catalogId:string){if(this.state.gameStarted)throw Error("Distribuição inicial só pode ocorrer antes do início.");if(!this.state.rules.initialPropertyDistribution)throw Error("Distribuição inicial não está habilitada no Ruleset.");return this.purchaseAsset(playerId,catalogId);}
  adminAdjustAsset(playerId:string,assetId:string,target:number){const {asset}=this.asset(playerId,assetId);if(asset.kind!=="property")throw Error("Ajuste de construção só vale para propriedade.");if(!Number.isInteger(target)||target<0||target>5)throw Error("Nível inválido.");const old=asset.development;asset.development=target;this.syncHouseStock();try{this.assertInvariants();}catch(e){asset.development=old;this.syncHouseStock();throw e;}return asset;}

  pauseTimer(now=Date.now()){if(!this.state.rules.timedGame||!this.state.gameStarted||this.state.pausedAt)return;this.state.pausedAt=now;}
  resumeTimer(now=Date.now()){if(!this.state.pausedAt)return;this.state.totalPausedMs+=Math.max(0,now-this.state.pausedAt);this.state.pausedAt=0;}
  remainingTime(now=Date.now()){if(!this.state.rules.timedGame||!this.state.startedAt)return 0;const reference=this.state.pausedAt||now;return Math.max(0,this.state.durationMs-(reference-this.state.startedAt-this.state.totalPausedMs));}
  checkTimedGame(now=Date.now()){if(!this.state.rules.timedGame||!this.state.gameStarted||this.state.gamePhase==="FINISHED"||this.remainingTime(now)>0)return null;const candidates=[...this.state.players.values()].filter(p=>!p.bankrupt);if(!candidates.length)return null;const scored=candidates.map(p=>({p,value:this.metrics(p.id).liquidation})).sort((a,b)=>b.value-a.value);if(scored.length>1&&scored[0].value===scored[1].value){this.state.requiredAction="TIMED_GAME_TIE";this.state.requiredActionPlayerId="";return{tie:true,value:scored[0].value};}return this.finishGame(scored[0].p.id,"TIME_LIMIT");}
  evaluateVictory(){if(!this.state.gameStarted||this.state.gamePhase==="FINISHED")return null;const alive=[...this.state.players.values()].filter(p=>!p.bankrupt);if(this.state.players.size>=2&&alive.length===1)return this.finishGame(alive[0].id,"LAST_SOLVENT_PLAYER");return null;}
  finishByLiquidation(){if(!this.state.rules.alternateLiquidationVictory)throw Error("Final alternativo por liquidação não está habilitado nesta sala.");if(!this.state.gameStarted)throw Error("A partida ainda não foi iniciada.");if(this.state.gamePhase==="FINISHED")throw Error("A partida já foi encerrada.");const candidates=[...this.state.players.values()].filter(p=>!p.bankrupt);if(!candidates.length)throw Error("Não há jogador elegível para o encerramento.");const ranked=candidates.map(p=>({p,value:this.metrics(p.id).liquidation})).sort((a,b)=>b.value-a.value);if(ranked.length>1&&ranked[0].value===ranked[1].value){this.state.requiredAction="LIQUIDATION_TIE_BREAK";this.state.requiredActionPlayerId="";throw Error("Empate no valor de liquidação. Resolva o desempate nos dados conforme a regra opcional antes de encerrar.");}return this.finishGame(ranked[0].p.id,"ALTERNATE_LIQUIDATION");}
  finishGame(winnerId:string,reason:string){this.player(winnerId);this.state.winnerId=winnerId;this.state.gamePhase="FINISHED";this.state.gameFinishedAt=Date.now();this.state.requiredAction="";this.state.requiredActionPlayerId="";this.state.requiredLiabilityId="";return{winnerId,reason};}

  startHouseAuction(){if(!this.state.rules.limitedHouseStock)throw Error("Leilão de casa requer estoque limitado.");if(!this.state.houseAuctionAvailable||this.state.housesRemaining<1)throw Error("Não existe casa retornada disponível para leilão.");if(this.state.houseAuctionStatus==="active")throw Error("Já existe leilão de casa ativo.");this.state.houseAuctionId=uid();this.state.houseAuctionStatus="active";this.state.houseAuctionBid=0;this.state.houseAuctionBidderId="";this.state.houseAuctionAssetId="";return this.state.houseAuctionId;}
  bidHouseAuction(playerId:string,assetId:string,amount:number){if(this.state.houseAuctionStatus!=="active")throw Error("Não há leilão de casa ativo.");const p=this.player(playerId);this.ensureActive(p);if(!Number.isFinite(amount)||amount<=this.state.houseAuctionBid||p.balance<amount)throw Error("Lance inválido ou saldo insuficiente.");const {asset}=this.asset(playerId,assetId);if(asset.development>=5)throw Error("Escolha propriedade que ainda possa receber desenvolvimento.");const next=asset.development===this.state.rules.housesBeforeCondo?5:asset.development+1;this.developmentPlan(playerId,assetId,next);this.state.houseAuctionBid=Math.round(amount);this.state.houseAuctionBidderId=p.id;this.state.houseAuctionAssetId=asset.id;return this.state.houseAuctionBid;}
  closeHouseAuction(){if(this.state.houseAuctionStatus!=="active")throw Error("Não há leilão ativo.");if(!this.state.houseAuctionBidderId){this.state.houseAuctionStatus="cancelled";return{winnerId:"",amount:0};}const p=this.player(this.state.houseAuctionBidderId),{asset}=this.asset(p.id,this.state.houseAuctionAssetId),target=asset.development===this.state.rules.housesBeforeCondo?5:asset.development+1,plan=this.developmentPlan(p.id,asset.id,target);if(p.balance<this.state.houseAuctionBid)throw Error("Vencedor não possui mais saldo para honrar o lance.");p.balance-=this.state.houseAuctionBid;p.bankOps++;asset.development=target;if(plan.delta>0)p.stats.housesBuilt+=plan.delta;this.syncHouseStock();const result={winnerId:p.id,amount:this.state.houseAuctionBid,assetId:asset.id};this.state.houseAuctionStatus="closed";this.state.houseAuctionAvailable=false;this.assertInvariants();return result;}

  metrics(playerId:string){const p=this.player(playerId),assets=[...p.assets];return{balance:p.balance,nominal:nominalAssets(assets),invested:investedValue(assets,this.state.rules.housesBeforeCondo),liquidation:liquidationValue(p.balance,assets,this.state.rules.housesBeforeCondo),assetCount:assets.length};}
}
