import type { Client, Room } from "@colyseus/core";
import { parseAdminAdjust, parseBankruptcy, parseHouseAuctionBid, parseInitialDistributionAdmin, parseJailAction, parsePlayerTarget, parseRestoreBankruptcy, parseRoomName, parseTransferAdmin, parseTurnOrder } from "../../protocol/messages.js";
import type { RoomRuntime } from "../runtime.js";

export function adminHandlers(rt:RoomRuntime,room:Room<any>){
  const startTurns=(client:Client,data:unknown)=>{if(!rt.requireAdmin(client))return;try{const x=parseTurnOrder(data),current=rt.engine.startTurnTracker(x.order.length?x.order:[...rt.state.players.keys()]);rt.event({code:"TURN_TRACKER_STARTED",category:"turn",actorId:rt.me(client).id,targetPlayerId:current,message:`Rastreador de turnos iniciado. Primeiro jogador: ${rt.state.players.get(current)?.name}.`});}catch(e){client.send("error",(e as Error).message);}};
  const endTurn=(client:Client)=>{const p=rt.active(client);if(!p)return;try{const next=rt.engine.endTurn(p.id);rt.event({code:"TURN_ENDED",category:"turn",actorId:p.id,targetPlayerId:next,message:next===p.id?`${p.name} tirou dupla e permanece na vez.`:`${p.name} encerrou a jogada. Agora é a vez de ${rt.state.players.get(next)?.name}.`});}catch(e){client.send("error",(e as Error).message);}};
  const rollAssistiveDice=(client:Client)=>{const p=rt.active(client);if(!p)return;try{const r=rt.dispatcher.dispatch({type:"ROLL_ASSISTIVE_DICE",playerId:p.id});rt.event({code:r.sentToJail?"JAIL_ENTERED":r.releasedFromJail?"JAIL_EXITED":"DICE_ROLLED",category:"turn",actorId:p.id,message:r.sentToJail?`${p.name} tirou a terceira dupla consecutiva e foi para a cadeia.`:r.releasedFromJail?`${p.name} saiu da cadeia com dupla ${r.first}+${r.second}; mova o peão físico usando este resultado.`:`${p.name} tirou ${r.first} e ${r.second}${r.doubles?" (dupla)":""}; mova o peão físico.`,metadata:r});client.send("dice_result",r);}catch(e){client.send("error",(e as Error).message);}};
  const jail=(client:Client,data:unknown)=>{let x;try{x=parseJailAction(data);}catch(e){return client.send("error",(e as Error).message);}const self=rt.me(client),targetId=x.playerId||self.id;try{if(x.action==="send"||x.action==="visit"){if(targetId!==self.id&&!rt.requireAdmin(client))return;x.action==="send"?rt.engine.sendToJail(targetId):rt.engine.markJailVisit(targetId);}else if(x.action==="failed_roll")rt.engine.failedJailAttempt(self.id);else if(x.action==="pay_fine"){const r=rt.dispatcher.dispatch({type:"PAY_JAIL_FINE",playerId:self.id});if(r.status==="liability")client.send("liquidity_required",rt.engine.liquidity(self.id,r.liabilityId));}else if(x.action==="habeas")rt.engine.useHabeas(self.id);else if(x.action==="grant_habeas"){if(!rt.requireAdmin(client))return;rt.engine.grantHabeas(targetId);}rt.event({code:`JAIL_${x.action.toUpperCase()}`,category:"jail",actorId:self.id,targetPlayerId:targetId,message:`Estado de cadeia atualizado para ${rt.state.players.get(targetId)?.name||"jogador"}.`,metadata:{requiredAction:rt.state.requiredAction,requiredLiabilityId:rt.state.requiredLiabilityId}});}catch(e){client.send("error",(e as Error).message);}};
  const adjust=(client:Client,data:unknown)=>{if(!rt.requireAdmin(client))return;try{const x=parseAdminAdjust(data),a=rt.engine.adminAdjustAsset(x.playerId,x.assetId,x.development);rt.event({code:"ADMIN_STATE_ADJUSTMENT",category:"admin",actorId:rt.me(client).id,targetPlayerId:x.playerId,catalogId:a.catalogId,message:`Ajuste administrativo de estado físico aplicado em ${a.name}.`,metadata:{development:a.development}});}catch(e){client.send("error",(e as Error).message);}};
  const requestBankruptcy=(client:Client,data:unknown)=>{const p=rt.active(client);if(!p)return;try{const x=parseBankruptcy(data);if(x.playerId&&x.playerId!==p.id)throw Error("Jogador inválido para solicitação.");const liq=rt.engine.liquidity(p.id,x.liabilityId);if(!liq.canDeclareBankruptcy)throw Error("Ainda existem opções de liquidez antes da falência.");rt.pend("bankruptcy",p,rt.state.players.get(rt.state.hostId),{catalogId:x.liabilityId,reason:"Solicitação de falência após central de liquidez"});rt.event({code:"BANKRUPTCY_REQUESTED",category:"bankruptcy",actorId:p.id,message:`${p.name} solicitou declaração de falência após avaliar a obrigação selecionada.`,metadata:{liabilityId:x.liabilityId}});}catch(e){client.send("error",(e as Error).message);}};
  const declareBankruptcy=(client:Client,data:unknown)=>{if(!rt.requireAdmin(client))return;try{const x=parseBankruptcy(data),playerId=x.playerId||rt.me(client).id,r=rt.dispatcher.dispatch({type:"DECLARE_BANKRUPTCY",playerId,liabilityId:x.liabilityId});rt.event({code:"BANKRUPTCY",category:"bankruptcy",actorId:rt.me(client).id,targetPlayerId:playerId,amount:r.paid,message:`${rt.state.players.get(playerId)?.name} foi declarado falido; peças devolvidas e liquidação processada.`,metadata:r});if(rt.state.winnerId)rt.event({code:"GAME_FINISHED",category:"victory",actorId:rt.state.winnerId,message:`${rt.state.players.get(rt.state.winnerId)?.name} é o Grande Milionário: único jogador não falido.`});}catch(e){client.send("error",(e as Error).message);}};
  const restoreBankruptcy=(client:Client,data:unknown)=>{if(!rt.requireAdmin(client))return;try{const {playerId:id}=parseRestoreBankruptcy(data);rt.engine.restoreBankruptcy(id);rt.event({code:"BANKRUPTCY_RESTORED",category:"admin",actorId:rt.me(client).id,targetPlayerId:id,message:`Falência de ${rt.state.players.get(id)?.name} desfeita por ferramenta administrativa.`});}catch(e){client.send("error",(e as Error).message);}};
  const transferAdmin=(client:Client,data:unknown)=>{if(!rt.requireAdmin(client))return;let x;try{x=parseTransferAdmin(data);}catch(e){return client.send("error",(e as Error).message);}const current=rt.me(client),next=rt.state.players.get(x.playerId);if(!next||next.id===current.id||!next.connected)return client.send("error","Selecione outro jogador online.");rt.state.hostId=next.id;rt.event({code:"ADMIN_TRANSFERRED",category:"admin",actorId:current.id,targetPlayerId:next.id,message:`${current.name} transferiu a administração para ${next.name}.`});room.broadcast("admin_transferred",{from:current.name,to:next.name});};
  const toggleLock=(client:Client)=>{if(!rt.requireAdmin(client))return;rt.state.locked=!rt.state.locked;rt.event({code:"ROOM_LOCK_CHANGED",category:"admin",actorId:rt.me(client).id,message:rt.state.locked?"Entradas de novos jogadores bloqueadas; recuperação legítima continua permitida.":"Entradas reabertas."});};
  const settings=(client:Client,data:unknown)=>{if(!rt.requireAdmin(client))return;let x;try{x=parseRoomName(data);}catch(e){return client.send("error",(e as Error).message);}const name=x.name;if(name&&name!==rt.state.roomName){rt.state.roomName=name;rt.event({code:"ROOM_SETTINGS_CHANGED",category:"admin",actorId:rt.me(client).id,message:"Nome da partida atualizado."});}};
  const kick=(client:Client,data:unknown)=>{if(!rt.requireAdmin(client))return;let x;try{x=parsePlayerTarget(data);}catch(e){return client.send("error",(e as Error).message);}const id=x.id,p=rt.state.players.get(id),connection=room.clients.find(c=>rt.sessionToPlayer.get(c.sessionId)===id);if(!p||!connection||id===rt.me(client).id)return client.send("error","Jogador inválido.");p.connected=false;rt.sessionToPlayer.delete(connection.sessionId);rt.event({code:"PLAYER_CONNECTION_KICKED",category:"admin",actorId:rt.me(client).id,targetPlayerId:id,message:`A conexão de ${p.name} foi expulsa pelo ADM; perfil, patrimônio e obrigações foram preservados.`});connection.send("kicked","Sua conexão foi removida pelo ADM. O perfil foi preservado e pode ser recuperado.");connection.leave(4000);};
  const markAbandoned=(client:Client,data:unknown)=>{if(!rt.requireAdmin(client))return;let x;try{x=parsePlayerTarget(data);}catch(e){return client.send("error",(e as Error).message);}const id=x.id,p=rt.state.players.get(id);if(!p||p.connected)return client.send("error","Somente perfil offline pode ser marcado como abandonado.");p.abandoned=true;rt.event({code:"PLAYER_ABANDONED",category:"admin",actorId:rt.me(client).id,targetPlayerId:id,message:`${p.name} foi marcado como abandonado. Isso não equivale a falência e o estado financeiro foi preservado.`});};
  const removeOffline=(client:Client,data:unknown)=>markAbandoned(client,data);
  const initialDistribution=(client:Client,data:unknown)=>{if(!rt.requireAdmin(client))return;try{const {playerId,catalogId}=parseInitialDistributionAdmin(data),a=rt.engine.assignInitialAsset(playerId,catalogId);rt.event({code:"INITIAL_PROPERTY_DISTRIBUTED",category:"setup",actorId:rt.me(client).id,targetPlayerId:playerId,catalogId:a.catalogId,amount:a.purchase,message:`${a.name} foi distribuída a ${rt.state.players.get(playerId)?.name} antes do início, com pagamento ao banco.`});}catch(e){client.send("error",(e as Error).message);}};
  const startAuction=(client:Client)=>{if(!rt.requireAdmin(client))return;try{const id=rt.engine.startHouseAuction();rt.event({code:"HOUSE_AUCTION_STARTED",category:"development",actorId:rt.me(client).id,message:"ADM iniciou leilão de uma casa retornada após escassez.",metadata:{auctionId:id,behavior:"APP_BEHAVIOR: lance substitui o custo normal da peça leiloada"}});}catch(e){client.send("error",(e as Error).message);}};
  const bidAuction=(client:Client,data:unknown)=>{const p=rt.active(client);if(!p)return;try{const x=parseHouseAuctionBid(data),amount=rt.engine.bidHouseAuction(p.id,x.assetId,x.amount);rt.event({code:"HOUSE_AUCTION_BID",category:"development",actorId:p.id,amount,message:`${p.name} ofertou ${amount.toLocaleString("pt-BR")} no leilão de casa.`});}catch(e){client.send("error",(e as Error).message);}};
  const closeAuction=(client:Client)=>{if(!rt.requireAdmin(client))return;try{const r=rt.engine.closeHouseAuction();rt.event({code:"HOUSE_AUCTION_FINISHED",category:"development",actorId:rt.me(client).id,targetPlayerId:r.winnerId,amount:r.amount,message:r.winnerId?`${rt.state.players.get(r.winnerId)?.name} venceu o leilão de casa por ${r.amount.toLocaleString("pt-BR")}.`:"Leilão encerrado sem lances.",metadata:r});}catch(e){client.send("error",(e as Error).message);}};
  const finishByLiquidation=(client:Client)=>{if(!rt.requireAdmin(client))return;try{const r=rt.engine.finishByLiquidation(),winner=rt.state.players.get(r.winnerId)!;rt.event({code:"GAME_FINISHED",category:"victory",actorId:winner.id,message:`${winner.name} venceu pelo maior valor de liquidação.`,metadata:r});room.broadcast("game_finished",{winnerId:winner.id,winnerName:winner.name,reason:r.reason});}catch(e){client.send("error",(e as Error).message);}};
  return{start_turns:startTurns,end_turn:endTurn,roll_assistive_dice:rollAssistiveDice,jail_action:jail,admin_adjust_asset:adjust,request_bankruptcy:requestBankruptcy,declare_bankruptcy:declareBankruptcy,restore_bankruptcy:restoreBankruptcy,transfer_admin:transferAdmin,toggle_lock:toggleLock,settings,kick,remove_offline:removeOffline,mark_abandoned:markAbandoned,initial_distribution:initialDistribution,start_house_auction:startAuction,bid_house_auction:bidAuction,close_house_auction:closeAuction,finish_by_liquidation:finishByLiquidation};
}
