import type { Client } from "@colyseus/core";
import { parseAdminLiability, parseId, parseLegacyDebt, parseLegacyOffer, parseLiquidity, parseSettlement, parseSettlementResponse, parseTrade, parseTradeResponse } from "../../protocol/messages.js";
import type { RoomRuntime } from "../runtime.js";

export function tradeHandlers(rt:RoomRuntime){
  const isFreeAssetTransfer=(t:any)=>t&&t.proposerCash===0&&t.recipientCash===0&&t.proposerHabeasCount===0&&t.recipientHabeasCount===0&&t.proposerAssetIds?.length===1&&t.recipientAssetIds?.length===0;
  const offeredAssetName=(t:any)=>{const proposer=rt.state.players.get(t?.proposerId);const id=t?.proposerAssetIds?.[0];return proposer?.assets.find(a=>a.id===id)?.name||"o título";};
  const propose=(client:Client,data:unknown)=>{const p=rt.active(client);if(!p)return;try{const x=parseTrade(data),t=rt.dispatcher.dispatch({type:"PROPOSE_TRADE",proposerId:p.id,...x});const recipient=rt.state.players.get(t.recipientId)!;if(isFreeAssetTransfer(t)){const name=offeredAssetName(t);rt.event({code:"PROPERTY_TRANSFER_OFFERED",category:"trade",actorId:p.id,targetPlayerId:recipient.id,message:`${p.name} ofereceu ${name} para ${recipient.name}.`,metadata:{tradeId:t.id}});}else rt.event({code:"TRADE_PROPOSED",category:"trade",actorId:p.id,targetPlayerId:recipient.id,message:`${p.name} propôs uma negociação para ${recipient.name}.`,metadata:{tradeId:t.id,proposerHabeas:t.proposerHabeasCount,recipientHabeas:t.recipientHabeasCount}});}catch(e){client.send("error",(e as Error).message);}};
  const respond=(client:Client,data:unknown)=>{const p=rt.active(client);if(!p)return;let x;try{x=parseTradeResponse(data);}catch(e){return client.send("error",(e as Error).message);}const trade=rt.state.trades.get(x.id);if(!trade)return client.send("error","Negociação inexistente.");const proposer=rt.state.players.get(trade.proposerId),gift=isFreeAssetTransfer(trade),assetName=offeredAssetName(trade);try{const r=rt.dispatcher.dispatch({type:"RESPOND_TRADE",playerId:p.id,tradeId:x.id,accept:x.accept});if(gift)rt.event({code:r.accepted?"PROPERTY_TRANSFER_ACCEPTED":"PROPERTY_TRANSFER_REJECTED",category:"trade",actorId:p.id,targetPlayerId:trade.proposerId,message:r.accepted?`${p.name} aceitou ${assetName}.`:`${p.name} recusou a transferência de ${assetName}.`});else rt.event({code:r.accepted?"TRADE_ACCEPTED":"TRADE_REJECTED",category:"trade",actorId:p.id,targetPlayerId:trade.proposerId,message:r.accepted?`${p.name} aceitou a negociação de ${proposer?.name||"jogador"}.`:`${p.name} recusou a negociação de ${proposer?.name||"jogador"}.`});}catch(e){if(x.accept&&p.id===trade.recipientId&&rt.state.trades.has(x.id)){rt.state.trades.delete(x.id);rt.markDirty();rt.event({code:"TRADE_INVALIDATED",category:"trade",actorId:p.id,targetPlayerId:trade.proposerId,message:`A negociação de ${proposer?.name||"jogador"} foi cancelada porque o estado do patrimônio mudou.`});}client.send("error",(e as Error).message);}};
  const cancel=(client:Client,data:unknown)=>{const p=rt.me(client);try{const x=parseId(data),trade=rt.state.trades.get(x.id),gift=isFreeAssetTransfer(trade),assetName=offeredAssetName(trade),target=trade?.recipientId||"";rt.engine.cancelTrade(p.id,x.id);rt.event({code:gift?"PROPERTY_TRANSFER_CANCELLED":"TRADE_CANCELLED",category:"trade",actorId:p.id,targetPlayerId:target,message:gift?`${p.name} cancelou a transferência de ${assetName}.`:`${p.name} cancelou uma negociação.`});}catch(e){client.send("error",(e as Error).message);}};
  const offer=(client:Client,data:unknown)=>{try{const x=parseLegacyOffer(data);propose(client,{recipientId:x.to,proposerAssetIds:[x.assetId],proposerCash:0,recipientCash:0,recipientAssetIds:[],proposerHabeasCount:0,recipientHabeasCount:0});}catch(e){client.send("error",(e as Error).message);}};
  const createLiability=(client:Client,data:unknown)=>{if(!rt.requireAdmin(client))return;try{const x=parseAdminLiability(data),debtorId=x.debtorId,creditorPlayerId=x.creditorPlayerId,creditorType:"PLAYER"|"BANK"=creditorPlayerId?"PLAYER":"BANK",l=rt.engine.createLiability({debtorId,creditorType,creditorPlayerId:creditorPlayerId||undefined,amount:x.amount,reason:x.reason||"Obrigação registrada pelo ADM",sourceCode:"ADMIN_OBLIGATION"});rt.event({code:"LIABILITY_CREATED",category:"liability",actorId:rt.me(client).id,targetPlayerId:debtorId,amount:l.amount,message:`Obrigação de ${l.amount.toLocaleString("pt-BR")} registrada para ${rt.state.players.get(debtorId)?.name||"jogador"}.`,metadata:{liabilityId:l.id}});}catch(e){client.send("error",(e as Error).message);}};
  const liquidity=(client:Client,data:unknown)=>{const p=rt.active(client);if(!p)return;try{const x=parseLiquidity(data);client.send("liquidity_state",rt.engine.liquidity(p.id,x.id));}catch(e){client.send("error",(e as Error).message);}};
  const settlement=(client:Client,data:unknown)=>{const p=rt.active(client);if(!p)return;try{const x=parseSettlement(data),s=rt.engine.proposeSettlement({debtorId:p.id,...x});rt.event({code:"SETTLEMENT_PROPOSED",category:"liability",actorId:p.id,targetPlayerId:s.creditorPlayerId,message:`${p.name} propôs um acordo para quitar obrigação.`,metadata:{settlementId:s.id,liabilityId:s.liabilityId}});}catch(e){client.send("error",(e as Error).message);}};
  const respondSettlement=(client:Client,data:unknown)=>{const p=rt.active(client);if(!p)return;try{const x=parseSettlementResponse(data),accepted=rt.engine.respondSettlement(p.id,x.id,x.accept);rt.event({code:accepted?"SETTLEMENT_ACCEPTED":"SETTLEMENT_REJECTED",category:"liability",actorId:p.id,message:accepted?`${p.name} aceitou o acordo.`:`${p.name} recusou o acordo.`});}catch(e){client.send("error",(e as Error).message);}};
  const cancelSettlement=(client:Client,data:unknown)=>{const p=rt.me(client);let x;try{x=parseId(data);}catch{return;}const s=rt.state.settlements.get(x.id);if(s&&s.debtorId===p.id){rt.state.settlements.delete(s.id);rt.event({code:"SETTLEMENT_CANCELLED",category:"liability",actorId:p.id,message:`${p.name} cancelou um acordo.`});}};
  const debt=(client:Client,data:unknown)=>{const p=rt.active(client);if(!p)return;try{const x=parseLegacyDebt(data),creditorId=x.creditorId,l=rt.engine.createLiability({debtorId:p.id,creditorType:"PLAYER",creditorPlayerId:creditorId,amount:x.originalAmount,reason:"Dívida registrada para acordo",sourceCode:"LEGACY_DEBT"}),s=rt.engine.proposeSettlement({debtorId:p.id,liabilityId:l.id,cash:x.cashOffered,assetIds:x.assetIds,note:x.note});rt.event({code:"SETTLEMENT_PROPOSED",category:"liability",actorId:p.id,targetPlayerId:creditorId,amount:l.amount,message:`${p.name} registrou uma obrigação e propôs acordo ao credor.`,metadata:{liabilityId:l.id,settlementId:s.id}});}catch(e){client.send("error",(e as Error).message);}};
  return{trade:propose,respond_trade:respond,cancel_trade:cancel,offer,create_liability:createLiability,liquidity,settlement,respond_settlement:respondSettlement,cancel_settlement:cancelSettlement,debt,respond_debt:respondSettlement,cancel_debt:cancelSettlement};
}
