import test from "node:test";import assert from "node:assert/strict";
import { RoomRuntime } from "../src/room/runtime.ts";import { createHandlers } from "../src/room/handlers/index.ts";import { stateWithPlayers,fakeClient } from "./helpers.ts";

test("handlers de produção roteiam compra para GameEngine e ignoram development adulterado",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("sa"),a=fakeClient("sb");rt.sessionToPlayer.set("sa","a");rt.sessionToPlayer.set("sb","b");const room:any={clients:[admin,a],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room);h.asset(a,{catalogId:"londres",development:5,reason:"teste"});const q=[...s.pending.values()][0];assert.equal(q.development,0);h.respond(admin,{id:q.id,accept:true});assert.equal(s.players.get("b")!.assets[0].development,0);});

test("trade handler permite somente destinatário aceitar e transfere bilateralmente",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),ca=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[ca,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room);const city=rt.engine.purchaseAsset("a","londres");h.trade(ca,{recipientId:"b",proposerCash:100000,recipientCash:50000,proposerAssetIds:[city.id],recipientAssetIds:[]});const t=[...s.trades.values()][0];h.respond_trade(ca,{id:t.id,accept:true});assert.ok(ca.messages.some((m:any)=>String(m.data).includes("Somente o destinatário")));h.respond_trade(cb,{id:t.id,accept:true});assert.equal(s.players.get("b")!.assets[0].catalogId,"londres");});

test("transferência voluntária sem saldo é recusada sem Pending nem Liability",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),ca=fakeClient("a1");rt.sessionToPlayer.set("a1","a");s.players.get("a")!.balance=100;const room:any={clients:[ca],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room);h.money(ca,{to:"b",amount:500,reason:"presente"});assert.equal(s.players.get("a")!.balance,100);assert.equal(s.pending.size,0);assert.equal(s.liabilities.size,0);assert.ok(ca.messages.some((m:any)=>m.type==="error"&&String(m.data).includes("Saldo insuficiente")));});

test("transferência só movimenta saldo após aceite e pode ser recusada ou cancelada",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),ca=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");s.players.get("a")!.balance=500000;s.players.get("b")!.balance=200000;const room:any={clients:[ca,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room);h.money(ca,{to:"b",amount:100000});let q=[...s.pending.values()][0];assert.equal(s.players.get("a")!.balance,500000);assert.equal(s.players.get("b")!.balance,200000);assert.equal(q.kind,"transfer");h.respond(cb,{id:q.id,accept:true});assert.equal(s.players.get("a")!.balance,400000);assert.equal(s.players.get("b")!.balance,300000);assert.equal(s.pending.size,0);assert.ok([...s.events].some(e=>e.code==="TRANSFER_ACCEPTED"));h.money(ca,{to:"b",amount:50000});q=[...s.pending.values()][0];h.respond(cb,{id:q.id,accept:false});assert.equal(s.players.get("a")!.balance,400000);assert.equal(s.players.get("b")!.balance,300000);assert.ok([...s.events].some(e=>e.code==="TRANSFER_REJECTED"));h.money(ca,{to:"b",amount:25000});q=[...s.pending.values()][0];h.cancel(ca,{id:q.id});assert.equal(s.pending.size,0);assert.equal(s.players.get("a")!.balance,400000);assert.ok([...s.events].some(e=>e.code==="TRANSFER_CANCELLED"));});

test("compra usa preço canônico e só conclui após aprovação do ADM",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),before=s.players.get("b")!.balance;h.asset(cb,{catalogId:"londres",purchase:1});const q=[...s.pending.values()][0];assert.equal(q.purchase,240000);assert.equal(s.players.get("b")!.assets.length,0);assert.equal(s.players.get("b")!.balance,before);assert.ok([...s.events].some(e=>e.code==="PURCHASE_REQUESTED"));h.respond(admin,{id:q.id,accept:true});assert.equal(s.players.get("b")!.assets[0].catalogId,"londres");assert.equal(s.players.get("b")!.balance,before-240000);assert.ok([...s.events].some(e=>e.code==="PURCHASE_APPROVED"));});

test("compra recusada não altera saldo nem proprietário",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),before=s.players.get("b")!.balance;h.asset(cb,{catalogId:"londres"});const q=[...s.pending.values()][0];h.respond(admin,{id:q.id,accept:false});assert.equal(s.players.get("b")!.assets.length,0);assert.equal(s.players.get("b")!.balance,before);assert.equal(rt.engine.assetOwnerByCatalog("londres"),undefined);assert.ok([...s.events].some(e=>e.code==="PURCHASE_REJECTED"));});

test("pró-labore do Início é solicitado sem turn tracker e depende do ADM",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),before=s.players.get("b")!.balance;assert.equal(s.gameStarted,false);assert.equal(s.currentPlayerId,"");h.start_bonus(cb);const q=[...s.pending.values()][0];assert.equal(q.kind,"start_bonus");assert.equal(q.amount,200000);assert.equal(s.players.get("b")!.balance,before);h.respond(admin,{id:q.id,accept:true});assert.equal(s.players.get("b")!.balance,before+200000);assert.ok([...s.events].some(e=>e.code==="START_BONUS_APPROVED"));});

test("pró-labore recusado não altera saldo",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),before=s.players.get("b")!.balance;h.start_bonus(cb);const q=[...s.pending.values()][0];h.respond(admin,{id:q.id,accept:false});assert.equal(s.players.get("b")!.balance,before);assert.ok([...s.events].some(e=>e.code==="START_BONUS_REJECTED"));});

test("cliente não consegue desativar grupo completo dentro do comando de construção",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),ca=fakeClient("a1");rt.sessionToPlayer.set("a1","a");const room:any={clients:[ca],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room);const city=rt.engine.purchaseAsset("a","londres");h.development(ca,{id:city.id,value:1,requireFullGroupForBuilding:false});assert.equal(city.development,0);assert.ok(ca.messages.some((m:any)=>m.type==="error"&&String(m.data).includes("todas as propriedades")));});


test("sem turn tracker, compra, transferência, construção, hipoteca, pró-labore e aluguel continuam disponíveis",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room);assert.equal(s.gameStarted,false);assert.equal(s.currentPlayerId,"");h.asset(cb,{catalogId:"londres"});let q=[...s.pending.values()][0];h.respond(admin,{id:q.id,accept:true});const london=s.players.get("b")!.assets[0];s.rules.requireFullGroupForBuilding=false;h.development(cb,{id:london.id,value:1});assert.equal(london.development,1);h.development(cb,{id:london.id,value:0});h.mortgage(cb,{id:london.id,action:"mortgage"});assert.equal(london.mortgaged,true);h.money(cb,{to:"a",amount:1000});q=[...s.pending.values()].find(x=>x.kind==="transfer")!;h.respond(admin,{id:q.id,accept:true});h.start_bonus(cb);q=[...s.pending.values()].find(x=>x.kind==="start_bonus")!;h.respond(admin,{id:q.id,accept:true});const rentAsset=rt.engine.purchaseAsset("a","cidade-cabo"),aBeforeRent=s.players.get("a")!.balance,bBeforeRent=s.players.get("b")!.balance;h.resolve_rent(cb,{catalogId:rentAsset.catalogId});const aAfterRent=s.players.get("a")!.balance,bAfterRent=s.players.get("b")!.balance;assert.ok(aAfterRent>aBeforeRent);assert.ok(bAfterRent<bBeforeRent);assert.equal(aAfterRent-aBeforeRent,bBeforeRent-bAfterRent);});