import test from "node:test";import assert from "node:assert/strict";
import { RoomRuntime } from "../src/room/runtime.ts";import { createHandlers } from "../src/room/handlers/index.ts";import { stateWithPlayers,fakeClient } from "./helpers.ts";

test("handlers de produção roteiam compra para GameEngine e ignoram development adulterado",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("sa"),a=fakeClient("sb");rt.sessionToPlayer.set("sa","a");rt.sessionToPlayer.set("sb","b");const room:any={clients:[admin,a],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room);h.asset(a,{catalogId:"londres",development:5,reason:"teste"});const q=[...s.pending.values()][0];assert.equal(q.development,0);h.respond(admin,{id:q.id,accept:true});assert.equal(s.players.get("b")!.assets[0].development,0);});

test("trade handler permite somente destinatário aceitar e transfere bilateralmente",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),ca=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[ca,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room);const city=rt.engine.purchaseAsset("a","londres");h.trade(ca,{recipientId:"b",proposerCash:100000,recipientCash:50000,proposerAssetIds:[city.id],recipientAssetIds:[]});const t=[...s.trades.values()][0];h.respond_trade(ca,{id:t.id,accept:true});assert.ok(ca.messages.some((m:any)=>String(m.data).includes("Somente o destinatário")));assert.ok(s.trades.has(t.id));h.respond_trade(cb,{id:t.id,accept:true});assert.equal(s.players.get("b")!.assets[0].catalogId,"londres");});

test("transferência voluntária sem saldo é recusada sem Pending nem Liability",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),ca=fakeClient("a1");rt.sessionToPlayer.set("a1","a");s.players.get("a")!.balance=100;const room:any={clients:[ca],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room);h.money(ca,{to:"b",amount:500,reason:"presente"});assert.equal(s.players.get("a")!.balance,100);assert.equal(s.pending.size,0);assert.equal(s.liabilities.size,0);assert.ok(ca.messages.some((m:any)=>m.type==="error"&&String(m.data).includes("Saldo insuficiente")));});

test("transferência só movimenta saldo após aceite e pode ser recusada ou cancelada",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),ca=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");s.players.get("a")!.balance=500000;s.players.get("b")!.balance=200000;const room:any={clients:[ca,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room);h.money(ca,{to:"b",amount:100000});let q=[...s.pending.values()][0];assert.equal(s.players.get("a")!.balance,500000);assert.equal(s.players.get("b")!.balance,200000);assert.equal(q.kind,"transfer");h.respond(cb,{id:q.id,accept:true});assert.equal(s.players.get("a")!.balance,400000);assert.equal(s.players.get("b")!.balance,300000);assert.equal(s.pending.size,0);assert.ok([...s.events].some(e=>e.code==="TRANSFER_ACCEPTED"));h.money(ca,{to:"b",amount:50000});q=[...s.pending.values()][0];h.respond(cb,{id:q.id,accept:false});assert.equal(s.players.get("a")!.balance,400000);assert.equal(s.players.get("b")!.balance,300000);assert.ok([...s.events].some(e=>e.code==="TRANSFER_REJECTED"));h.money(ca,{to:"b",amount:25000});q=[...s.pending.values()][0];h.cancel(ca,{id:q.id});assert.equal(s.pending.size,0);assert.equal(s.players.get("a")!.balance,400000);assert.ok([...s.events].some(e=>e.code==="TRANSFER_CANCELLED"));});

test("compra usa preço canônico e só conclui após aprovação do ADM",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),before=s.players.get("b")!.balance;h.asset(cb,{catalogId:"londres",purchase:1});const q=[...s.pending.values()][0];assert.equal(q.purchase,240000);assert.equal(s.players.get("b")!.assets.length,0);assert.equal(s.players.get("b")!.balance,before);assert.ok([...s.events].some(e=>e.code==="PURCHASE_REQUESTED"));h.respond(admin,{id:q.id,accept:true});assert.equal(s.players.get("b")!.assets[0].catalogId,"londres");assert.equal(s.players.get("b")!.balance,before-240000);assert.ok([...s.events].some(e=>e.code==="PURCHASE_APPROVED"));});

test("compra recusada não altera saldo nem proprietário",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),before=s.players.get("b")!.balance;h.asset(cb,{catalogId:"londres"});const q=[...s.pending.values()][0];h.respond(admin,{id:q.id,accept:false});assert.equal(s.players.get("b")!.assets.length,0);assert.equal(s.players.get("b")!.balance,before);assert.equal(rt.engine.assetOwnerByCatalog("londres"),undefined);assert.ok([...s.events].some(e=>e.code==="PURCHASE_REJECTED"));});

test("pró-labore do Início é solicitado sem turn tracker e depende do ADM",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),before=s.players.get("b")!.balance;assert.equal(s.gameStarted,false);assert.equal(s.currentPlayerId,"");h.start_bonus(cb);const q=[...s.pending.values()][0];assert.equal(q.kind,"start_bonus");assert.equal(q.amount,200000);assert.equal(s.players.get("b")!.balance,before);h.respond(admin,{id:q.id,accept:true});assert.equal(s.players.get("b")!.balance,before+200000);assert.ok([...s.events].some(e=>e.code==="START_BONUS_APPROVED"));});

test("pró-labore recusado não altera saldo",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),before=s.players.get("b")!.balance;h.start_bonus(cb);const q=[...s.pending.values()][0];h.respond(admin,{id:q.id,accept:false});assert.equal(s.players.get("b")!.balance,before);assert.ok([...s.events].some(e=>e.code==="START_BONUS_REJECTED"));});

test("cliente não consegue desativar grupo completo dentro do comando de construção",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),ca=fakeClient("a1");rt.sessionToPlayer.set("a1","a");const room:any={clients:[ca],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room);const city=rt.engine.purchaseAsset("a","londres");h.development(ca,{id:city.id,value:1,requireFullGroupForBuilding:false});assert.equal(city.development,0);assert.ok(ca.messages.some((m:any)=>m.type==="error"&&String(m.data).includes("todas as propriedades")));});


test("sem turn tracker, compra, transferência, construção, hipoteca, pró-labore e aluguel continuam disponíveis",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room);assert.equal(s.gameStarted,false);assert.equal(s.currentPlayerId,"");h.asset(cb,{catalogId:"londres"});let q=[...s.pending.values()][0];h.respond(admin,{id:q.id,accept:true});const london=s.players.get("b")!.assets[0];s.rules.requireFullGroupForBuilding=false;h.development(cb,{id:london.id,value:1});assert.equal(london.development,1);h.development(cb,{id:london.id,value:0});h.mortgage(cb,{id:london.id,action:"mortgage"});assert.equal(london.mortgaged,true);h.money(cb,{to:"a",amount:1000});q=[...s.pending.values()].find(x=>x.kind==="transfer")!;h.respond(admin,{id:q.id,accept:true});h.start_bonus(cb);q=[...s.pending.values()].find(x=>x.kind==="start_bonus")!;h.respond(admin,{id:q.id,accept:true});const rentAsset=rt.engine.purchaseAsset("a","cidade-cabo"),aBeforeRent=s.players.get("a")!.balance,bBeforeRent=s.players.get("b")!.balance;h.resolve_rent(cb,{catalogId:rentAsset.catalogId});const aAfterRent=s.players.get("a")!.balance,bAfterRent=s.players.get("b")!.balance;assert.ok(aAfterRent>aBeforeRent);assert.ok(bAfterRent<bBeforeRent);assert.equal(aAfterRent-aBeforeRent,bBeforeRent-bAfterRent);});
test("venda voluntária ao banco usa valor canônico, depende do ADM e título volta ao mercado",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),asset=rt.engine.purchaseAsset("b","londres"),p=s.players.get("b")!,before=p.balance,received=p.received;h.request_bank_sale(cb,{id:asset.id,value:999999999});const q=[...s.pending.values()][0];assert.equal(q.kind,"bank_sale");assert.equal(q.purchase,240000);assert.equal(p.assets.length,1);h.respond(admin,{id:q.id,accept:true});assert.equal(p.balance,before+240000);assert.equal(p.received,received+240000);assert.equal(p.assets.length,0);assert.equal(rt.engine.assetOwnerByCatalog("londres"),undefined);const after=p.balance;h.respond(admin,{id:q.id,accept:true});assert.equal(p.balance,after);h.asset(admin,{catalogId:"londres",purchase:1});const buy=[...s.pending.values()].find(x=>x.kind==="asset")!;h.respond(admin,{id:buy.id,accept:true});assert.equal(rt.engine.assetOwnerByCatalog("londres")?.id,"a");assert.ok([...s.events].some(e=>e.code==="BANK_SALE_APPROVED"));});

test("venda voluntária pode ser recusada ou cancelada sem alterar patrimônio",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),asset=rt.engine.purchaseAsset("b","cairo"),p=s.players.get("b")!,before=p.balance;h.request_bank_sale(cb,{id:asset.id});let q=[...s.pending.values()][0];h.respond(admin,{id:q.id,accept:false});assert.equal(p.balance,before);assert.equal(p.assets[0].id,asset.id);h.request_bank_sale(cb,{id:asset.id});q=[...s.pending.values()][0];h.cancel(cb,{id:q.id});assert.equal(s.pending.size,0);assert.equal(p.balance,before);assert.equal(p.assets[0].id,asset.id);assert.ok([...s.events].some(e=>e.code==="BANK_SALE_REJECTED"));assert.ok([...s.events].some(e=>e.code==="BANK_SALE_CANCELLED"));});

test("venda ao banco revalida estado, bloqueia hipoteca/construção e invalida pendência alterada",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),p=s.players.get("b")!,asset=rt.engine.purchaseAsset("b","cidade-cabo");asset.mortgaged=true;h.request_bank_sale(cb,{id:asset.id});assert.equal(s.pending.size,0);assert.ok(cb.messages.some((m:any)=>m.type==="error"&&String(m.data).includes("hipoteca")));asset.mortgaged=false;asset.development=1;h.request_bank_sale(cb,{id:asset.id});assert.equal(s.pending.size,0);assert.ok(cb.messages.some((m:any)=>m.type==="error"&&String(m.data).includes("construções")));asset.development=0;h.request_bank_sale(cb,{id:asset.id});const q=[...s.pending.values()][0],before=p.balance;asset.mortgaged=true;h.respond(admin,{id:q.id,accept:true});assert.equal(s.pending.size,0);assert.equal(p.assets.length,1);assert.equal(p.balance,before);assert.ok([...s.events].some(e=>e.code==="BANK_SALE_INVALIDATED"));});

test("instituição pode ser vendida voluntariamente ao banco",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[admin,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),asset=rt.engine.purchaseAsset("b","onu"),p=s.players.get("b")!,before=p.balance;h.request_bank_sale(cb,{id:asset.id});const q=[...s.pending.values()][0];assert.equal(q.purchase,200000);h.respond(admin,{id:q.id,accept:true});assert.equal(p.balance,before+200000);assert.equal(rt.engine.assetOwnerByCatalog("onu"),undefined);});

test("transferência gratuita reutiliza Trade, exige aceite e não altera saldos",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),ca=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[ca,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),asset=rt.engine.purchaseAsset("a","londres"),pa=s.players.get("a")!,pb=s.players.get("b")!,ba=pa.balance,bb=pb.balance;h.trade(ca,{recipientId:"b",proposerCash:0,recipientCash:0,proposerAssetIds:[asset.id],recipientAssetIds:[],proposerHabeasCount:0,recipientHabeasCount:0});const t=[...s.trades.values()][0];assert.equal(rt.engine.assetOwnerByCatalog("londres")?.id,"a");h.respond_trade(cb,{id:t.id,accept:true});assert.equal(rt.engine.assetOwnerByCatalog("londres")?.id,"b");assert.equal(pa.balance,ba);assert.equal(pb.balance,bb);assert.ok([...s.events].some(e=>e.code==="PROPERTY_TRANSFER_ACCEPTED"));});

test("transferência gratuita pode ser recusada ou cancelada",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),ca=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[ca,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),asset=rt.engine.purchaseAsset("a","cairo");const propose=()=>h.trade(ca,{recipientId:"b",proposerCash:0,recipientCash:0,proposerAssetIds:[asset.id],recipientAssetIds:[],proposerHabeasCount:0,recipientHabeasCount:0});propose();let t=[...s.trades.values()][0];h.respond_trade(cb,{id:t.id,accept:false});assert.equal(rt.engine.assetOwnerByCatalog("cairo")?.id,"a");propose();t=[...s.trades.values()][0];h.cancel_trade(ca,{id:t.id});assert.equal(s.trades.size,0);assert.equal(rt.engine.assetOwnerByCatalog("cairo")?.id,"a");assert.ok([...s.events].some(e=>e.code==="PROPERTY_TRANSFER_REJECTED"));assert.ok([...s.events].some(e=>e.code==="PROPERTY_TRANSFER_CANCELLED"));});

test("transferência gratuita bloqueia construção, hipoteca e revalida antes do aceite",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),ca=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[ca,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),asset=rt.engine.purchaseAsset("a","cidade-cabo");asset.development=1;h.trade(ca,{recipientId:"b",proposerCash:0,recipientCash:0,proposerAssetIds:[asset.id],recipientAssetIds:[]});assert.equal(s.trades.size,0);asset.development=0;asset.mortgaged=true;h.trade(ca,{recipientId:"b",proposerCash:0,recipientCash:0,proposerAssetIds:[asset.id],recipientAssetIds:[]});assert.equal(s.trades.size,0);asset.mortgaged=false;h.trade(ca,{recipientId:"b",proposerCash:0,recipientCash:0,proposerAssetIds:[asset.id],recipientAssetIds:[]});const t=[...s.trades.values()][0];asset.mortgaged=true;h.respond_trade(cb,{id:t.id,accept:true});assert.equal(s.trades.size,0);assert.equal(rt.engine.assetOwnerByCatalog("cidade-cabo")?.id,"a");assert.ok(cb.messages.some((m:any)=>m.type==="error"));assert.ok([...s.events].some(e=>e.code==="TRADE_INVALIDATED"));});

test("instituição pode ser transferida gratuitamente",()=>{const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),ca=fakeClient("a1"),cb=fakeClient("b1");rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");const room:any={clients:[ca,cb],broadcast(){},lock(){},unlock(){}};const h:any=createHandlers(rt,room),asset=rt.engine.purchaseAsset("a","onu"),ba=s.players.get("a")!.balance,bb=s.players.get("b")!.balance;h.trade(ca,{recipientId:"b",proposerCash:0,recipientCash:0,proposerAssetIds:[asset.id],recipientAssetIds:[]});const t=[...s.trades.values()][0];h.respond_trade(cb,{id:t.id,accept:true});assert.equal(rt.engine.assetOwnerByCatalog("onu")?.id,"b");assert.equal(s.players.get("a")!.balance,ba);assert.equal(s.players.get("b")!.balance,bb);});


test("venda invalidada registra categoria correta para propriedade e instituição",()=>{
  for(const [catalogId,expected] of [["cidade-cabo","property"],["onu","organization"]] as const){
    const s=stateWithPlayers("a","b"),rt=new RoomRuntime(s),admin=fakeClient("a1"),client=fakeClient("b1");
    rt.sessionToPlayer.set("a1","a");rt.sessionToPlayer.set("b1","b");
    const room:any={clients:[admin,client],broadcast(){},lock(){},unlock(){}},h:any=createHandlers(rt,room);
    const asset=rt.engine.purchaseAsset("b",catalogId);
    h.request_bank_sale(client,{id:asset.id});
    const q=[...s.pending.values()][0];
    asset.mortgaged=true;
    h.respond(admin,{id:q.id,accept:true});
    const event=[...s.events].filter(e=>e.code==="BANK_SALE_INVALIDATED").at(-1);
    assert.ok(event);assert.equal(event.category,expected);
  }
});
