import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";
const publicRoot=path.resolve(process.cwd(),"../client/public"),clientRoot=path.resolve(process.cwd(),"../client");
const read=(...parts:string[])=>fs.readFileSync(path.join(...parts),"utf8");

test("PWA 0.9.3 usa cache versionado, limpa caches antigos e preserva atualização controlada",()=>{const sw=read(publicRoot,"sw.js");assert.match(sw,/banco-mundo-pwa-0\.9\.3/);assert.match(sw,/caches\.delete/);assert.match(sw,/SKIP_WAITING/);assert.match(sw,/clients\.claim/);assert.doesNotMatch(sw,/cacheCurrentAppShell\(\)\.then\(\(\) => self\.skipWaiting\(\)\)/);});

test("primeiro clients.claim da PWA não recarrega uma sala recém-criada",()=>{const shell=read(clientRoot,"src","shell.js");assert.match(shell,/hadServiceWorkerControllerAtLoad/);assert.match(shell,/!hadServiceWorkerControllerAtLoad && !updateActivationRequested/);});

test("manifest mantém instalação standalone e ícones obrigatórios",()=>{const m=JSON.parse(read(publicRoot,"manifest.webmanifest"));assert.equal(m.name,"Banco Mundo Online");assert.equal(m.short_name,"Banco Mundo");assert.equal(m.id,"/");assert.equal(m.start_url,"/?source=pwa");assert.equal(m.scope,"/");assert.equal(m.display,"standalone");assert.ok(m.background_color);assert.ok(m.theme_color);assert.ok(m.icons.some((x:any)=>x.sizes==="192x192"&&String(x.type).includes("png")));assert.ok(m.icons.some((x:any)=>x.sizes==="512x512"&&String(x.type).includes("png")));assert.ok(m.icons.some((x:any)=>x.sizes==="512x512"&&String(x.purpose||"").includes("maskable")));});

test("theme-color do HTML e manifest permanecem consistentes",()=>{const m=JSON.parse(read(publicRoot,"manifest.webmanifest")),html=read(clientRoot,"index.html"),match=html.match(/<meta[^>]+name="theme-color"[^>]+content="([^"]+)"|<meta[^>]+content="([^"]+)"[^>]+name="theme-color"/);assert.ok(match);assert.equal(match[1]||match[2],m.theme_color);assert.match(html,/rel="apple-touch-icon"/);});

test("instalação progressiva cobre prompt nativo, fallback manual, standalone e appinstalled",()=>{const shell=read(clientRoot,"src","shell.js");assert.match(shell,/beforeinstallprompt/);assert.match(shell,/deferredInstallPrompt/);assert.match(shell,/deferredInstallPrompt\.prompt\(\)/);assert.match(shell,/userChoice/);assert.match(shell,/display-mode: standalone/);assert.match(shell,/navigator\.standalone === true/);assert.match(shell,/appinstalled/);assert.match(shell,/Banco Mundo instalado com sucesso/);assert.match(shell,/Adicionar à Tela de Início/);assert.match(shell,/Instalar aplicativo/);assert.match(shell,/Adicionar à tela inicial/);});

test("instalação e atualização da PWA continuam estados independentes",()=>{const shell=read(clientRoot,"src","shell.js");assert.match(shell,/#installApp/);assert.match(shell,/#updateApp/);assert.match(shell,/waitingServiceWorker/);assert.match(shell,/updateActivationRequested/);assert.doesNotMatch(shell,/installButton.*updateApp/);});
