import { escapeHtml as esc } from "../ui/safe.js";
import { schemaEntries } from "../ui/schema-safe.js";
import { synchronizedRules } from "./ruleset.js";
function developmentValue(asset,housesBeforeCondo){const level=Math.max(0,Math.min(5,Number(asset.development)||0));return level===5?housesBeforeCondo*Number(asset.houseCost||0)+Number(asset.condominiumCost||0):level*Number(asset.houseCost||0);}
function constructionLiquidation(asset,housesBeforeCondo){if(asset.kind!=="property")return 0;const level=Math.max(0,Math.min(5,Number(asset.development)||0));if(level===5)return Math.floor(Number(asset.houseCost||0)/2)*housesBeforeCondo+Math.floor(Number(asset.condominiumCost||0)/2);return Math.floor(Number(asset.houseCost||0)/2)*level;}
export function playerMetrics(player,rules){const housesBeforeCondo=Number(rules?.housesBeforeCondo)===3?3:4,assets=player?.assets?[...player.assets]:[],propertyCount=assets.filter(a=>a.kind==="property").length,organizationCount=assets.filter(a=>a.kind==="organization").length,nominal=assets.reduce((s,a)=>s+Number(a.purchase||0),0),invested=assets.reduce((s,a)=>s+(a.kind==="property"?developmentValue(a,housesBeforeCondo):0),0),liquidationAssets=assets.reduce((s,a)=>s+(a.mortgaged?0:Number(a.purchase||0))+constructionLiquidation(a,housesBeforeCondo),0);const developmentPieces=assets.reduce((sum,a)=>sum+(a.kind!=="property"?0:Number(a.development)===5?housesBeforeCondo+1:Number(a.development)||0),0);return{money:Number(player.balance||0),nominal,invested,liquidation:Number(player.balance||0)+liquidationAssets,assetCount:assets.length,propertyCount,organizationCount,developmentPieces};}
function markup(players,value,detail,me){return players.map(({id,player,metrics:m},i)=>`<li class="ranking-item ${id===me?"me":""}"><span class="rank-position">${i+1}º</span><span>${esc(player.name)}${id===me?" (você)":""}${player.bankrupt?" • 🔒 Falido":""}<small class="small">${detail(m)}</small></span><strong>${value(m)}</strong></li>`).join("");}
function sorted(players,key){return [...players].sort((a,b)=>b.metrics[key]-a.metrics[key]||a.player.name.localeCompare(b.player.name,"pt-BR"));}
export function renderRankings({room,me,$,fmt}){if(!room?.state?.players)return;const players=schemaEntries(room.state.players).map(([id,player])=>({id,player,metrics:playerMetrics(player,synchronizedRules(room))})),sets=[
  ["rankLiquidation",sorted(players,"liquidation"),m=>fmt(m.liquidation),()=>"<br>Saldo + valor realizável segundo as regras"],
  ["rankMoney",sorted(players,"money"),m=>fmt(m.money),()=>"<br>Dinheiro disponível"],
  ["rankNominal",sorted(players,"nominal"),m=>fmt(m.nominal),()=>"<br>Valor de compra dos títulos"],
  ["rankInvested",sorted(players,"invested"),m=>fmt(m.invested),()=>"<br>Valor investido em construções"],
  ["rankAssets",[...players].sort((a,b)=>b.metrics.assetCount-a.metrics.assetCount||b.metrics.liquidation-a.metrics.liquidation||a.player.name.localeCompare(b.player.name,"pt-BR")),m=>String(m.assetCount),m=>`<br>${m.propertyCount} propriedades • ${m.organizationCount} instituições`]
];for(const[id,list,value,detail]of sets){const el=$("#"+id);if(el)el.innerHTML=markup(list,value,detail,me);}}
