export function createRecoveryTools({$,getRoom,getMe,toast,sessionKey,getCode,setCode}){
  let hideTimer;
  const stored=()=>{const code=getCode();if(code)return code;try{return JSON.parse(localStorage.getItem(sessionKey)||"{}").recoveryCode||"";}catch{return"";}};
  const update=(show=false)=>{const code=stored();let storedName="";try{storedName=JSON.parse(localStorage.getItem(sessionKey)||"{}").name||"";}catch{}const room=getRoom(),me=getMe(),name=room?.state?.players?.get(me)?.name||storedName,nameBox=$("#myProfileName"),codeBox=$("#myRecoveryCode"),toggle=$("#toggleRecovery");if(!nameBox||!codeBox||!toggle)return;nameBox.textContent=name?`Jogador: ${name}`:"";codeBox.textContent=show&&code?code:code?"••••••••":"Código ainda não disponível";codeBox.dataset.visible=show&&code?"true":"false";toggle.textContent=show&&code?"Ocultar código":"Ver código de recuperação";clearTimeout(hideTimer);if(show&&code)hideTimer=setTimeout(()=>update(false),20000);};
  const write=async text=>{if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(text);const area=document.createElement("textarea");area.value=text;area.style.position="fixed";area.style.opacity="0";document.body.appendChild(area);area.select();document.execCommand("copy");area.remove();};
  const copy=async()=>{const code=stored();if(!code)return toast("Código pessoal ainda não disponível.");try{await write(code);toast("Código pessoal copiado.");}catch{toast("Não foi possível copiar. Use Mostrar código.");}};
  const share=async()=>{const code=stored();if(!code)return toast("Código pessoal ainda não disponível.");const room=getRoom(),name=room?.state?.players?.get(getMe())?.name||"Jogador",text=`Banco Mundo Online\nJogador: ${name}\nCódigo pessoal de recuperação: ${code}\n\nGuarde em local privado.`;if(navigator.share){try{await navigator.share({title:"Meu código de recuperação",text});return;}catch(error){if(error?.name==="AbortError")return;}}try{await write(text);toast("Dados de recuperação copiados.");}catch{toast("Não foi possível compartilhar ou copiar.");}};
  const handleRecovered=d=>{if(d?.recoveryCode)setCode(d.recoveryCode);const room=getRoom(),s=JSON.parse(localStorage.getItem(sessionKey)||"{}");s.recoveryCode=getCode();s.saveCode=room?.state?.saveCode||s.saveCode;localStorage.setItem(sessionKey,JSON.stringify(s));update();};
  return{stored,update,copy,share,handleRecovered};
}
