import crypto from "node:crypto";
import { Client, Room } from "@colyseus/core";
import { Player, State } from "./state.js";
import { APP_VERSION } from "./version.js";
import { secureToken, hashToken, safeEqualHash, hashPin, verifyPin, validatePin } from "./domain/security.js";
import { isOfficialRules, normalizeRules } from "./domain/ruleset.js";
import { atomicSave, code, loadSaveWithFallback, restore, sanitizeForExport, serialize, SaveConflictError } from "./persistence.js";
import { acquireRoomLease, databaseEnabled, recordSharedRateLimit, releaseRoomLease, renewRoomLease } from "./database.js";
import { RoomRuntime } from "./room/runtime.js";
import { createHandlers } from "./room/handlers/index.js";
import { text } from "./domain/commands.js";

const recentCreateOperations=new Map<string,number>(),CREATE_OPERATION_WINDOW_MS=120_000;
function reserveCreateOperation(operationId:unknown){const id=text(operationId,80);if(!id)return;const now=Date.now();for(const[k,at]of recentCreateOperations)if(now-at>CREATE_OPERATION_WINDOW_MS)recentCreateOperations.delete(k);if(recentCreateOperations.has(id))throw Error("Esta tentativa de criação já foi processada.");recentCreateOperations.set(id,now);}
type CreateOptions={pin?:string;resumeCode?:string;operationId?:string;mode?:"assisted"|"complete";rules?:unknown};
type JoinOptions={name?:string;pin?:string;deviceToken?:string;recoveryCode?:string};

export class BankRoom extends Room<{state:State}>{
  maxClients=6;autoDispose=false;
  private pinHash="";private rt!:RoomRuntime;private saveTimer:ReturnType<typeof setTimeout>|null=null;private saveChain:Promise<void>=Promise.resolve();private authFailures=new Map<string,number[]>();private pendingRecoveryBySession=new Map<string,string>();private persistenceConflict=false;private hostSuccessionTimer:ReturnType<typeof setTimeout>|null=null;

  async onCreate(options:CreateOptions){
    if(options.resumeCode){const raw=await loadSaveWithFallback(text(options.resumeCode,40));this.pinHash=String(raw.pinHash||"");this.setState(restore(raw));}
    else{reserveCreateOperation(options.operationId);const pin=text(options.pin,32);this.pinHash=pin?(validatePin(pin),await hashPin(pin)):"";if(options.mode==="complete")throw Error("Modo Jogo Completo indisponível: ordem oficial do tabuleiro e conteúdo das 32 cartas Sorte-Revés continuam SOURCE_MISSING.");const state=new State();state.saveCode=code();state.mode="assisted";const rulesInput=options.rules&&typeof options.rules==="object"?options.rules as Record<string,unknown>:undefined,preset=rulesInput?.preset,presetValue=preset==="official"||preset==="custom"||preset==="legacy"?preset:undefined;const normalized=normalizeRules(rulesInput,presetValue);normalized.preset=isOfficialRules(normalized)?"official":"custom";Object.assign(state.rules,normalized);state.rulesSnapshot=JSON.stringify(normalized);this.setState(state);}
    // Saves 0.8/0.9 antigos não possuem `rulesSnapshot`; derive sempre do Ruleset restaurado.
    const activePreset=this.state.rules.preset==="legacy"?"legacy":this.state.rules.preset==="custom"?"custom":"official";
    this.state.rulesSnapshot=JSON.stringify(normalizeRules(this.state.rules,activePreset));
    if(!(await acquireRoomLease(this.state.saveCode)))throw Error("Esta partida já está ativa em outra instância. Aguarde a expiração do lease ou conecte à instância que possui a sala.");
    this.rt=new RoomRuntime(this.state);this.rt.markDirty();
    if(!options.resumeCode){const rulesPlain=JSON.parse(JSON.stringify(this.state.rules)),rulesetHash=crypto.createHash("sha256").update(JSON.stringify(rulesPlain)).digest("hex");this.rt.event({code:"RULESET_SELECTED",category:"system",message:this.state.rules.preset==="official"?"Partida criada com regras oficiais.":"Partida criada com regras personalizadas.",metadata:{rulesetHash,rules:rulesPlain}});}
    const handlers={...createHandlers(this.rt,this),client_ready:this.clientReady,report:this.report,backup:this.backup,pause_room:this.pauseRoom,resume_room:this.resumeRoom,end_room:this.endRoom};
    for(const[message,handler]of Object.entries(handlers))this.onMessage(message,(client:Client,data:unknown)=>{if(this.persistenceConflict)return client.send("error","Sala pausada por conflito de persistência. Nenhuma mutação é aceita até recuperação administrativa.");try{(handler as any).call(this,client,data);}catch(e){client.send("error",e instanceof Error?e.message:"Operação inválida.");}if(this.rt.isDirty())this.scheduleSave();});
    this.setSimulationInterval(()=>{void this.maintenanceTick();},15_000);
    await this.saveNow(true);
  }

  private async maintenanceTick(){if(!(await renewRoomLease(this.state.saveCode))){this.handlePersistenceConflict("LEASE_LOST");return;}const before=this.state.winnerId,result=this.rt.engine.checkTimedGame();if(result&&this.state.winnerId&&!before){this.rt.event({code:"GAME_FINISHED",category:"victory",actorId:this.state.winnerId,message:`${this.state.players.get(this.state.winnerId)?.name} venceu a partida contra o relógio.`,metadata:result});this.broadcast("game_finished",result);}if(this.rt.isDirty())await this.saveNow();}
  private profileByRecovery(value:unknown){const recovery=text(value,200);if(!recovery)return undefined;const hash=hashToken(recovery);return[...this.state.players.values()].find(p=>safeEqualHash(p.recoveryTokenHash,hash));}
  private profileByDevice(value:unknown){const device=text(value,200);if(!device)return undefined;const hash=hashToken(device);return[...this.state.players.values()].find(p=>safeEqualHash(p.deviceTokenHash,hash));}
  private matchingProfile(options:JoinOptions){const recovery=text(options.recoveryCode,200);return recovery?this.profileByRecovery(recovery):this.profileByDevice(options.deviceToken);}
  private authRateKey(client:Client){const ip=String((client as any)?.ref?._socket?.remoteAddress||(client as any)?.ref?.socket?.remoteAddress||"unknown");return`${this.state?.saveCode||this.roomId||"room"}:${ip}`;}
  private async recordAuthFailure(client:Client,scope="pin"){const key=`${scope}:${this.authRateKey(client)}`,now=Date.now();if(databaseEnabled&&await recordSharedRateLimit(key,12,60_000))throw Error("Muitas tentativas de autenticação para esta sala/origem. Aguarde antes de tentar novamente.");const recent=(this.authFailures.get(key)||[]).filter(t=>now-t<60_000);recent.push(now);this.authFailures.set(key,recent);if(recent.length>12)throw Error("Muitas tentativas de autenticação para esta sala/origem. Aguarde antes de tentar novamente.");}

  async onAuth(client:Client,options:JoinOptions){const pin=text(options.pin,32);if(this.pinHash&&!pin)throw Error("PIN_REQUIRED");if(this.pinHash&&!await verifyPin(pin,this.pinHash)){await this.recordAuthFailure(client);throw Error("PIN incorreto.");}const profile=this.matchingProfile(options);if(text(options.recoveryCode,200)&&!profile){await this.recordAuthFailure(client,"recovery");throw Error("Código de recuperação inválido.");}if(this.state.ended)throw Error("Sala encerrada.");if(this.state.locked&&!profile)throw Error("Sala bloqueada para novos jogadores. Perfis existentes ainda podem ser recuperados.");return true;}
  private clientReady(client:Client){const profile=this.rt.playerForSession(client.sessionId);if(!profile)return;const recoveryCode=this.pendingRecoveryBySession.get(client.sessionId);client.send("profile_recovered",{name:profile.name,playerId:profile.id,recoveryCode:recoveryCode||undefined});this.pendingRecoveryBySession.delete(client.sessionId);}
  onJoin(client:Client,options:JoinOptions){const recovery=text(options.recoveryCode,200),profile=this.matchingProfile(options);if(recovery&&!profile)throw Error("Código de recuperação inválido.");if(profile){this.rt.sessionToPlayer.set(client.sessionId,profile.id);if(recovery)this.pendingRecoveryBySession.set(client.sessionId,recovery);profile.connected=true;profile.abandoned=false;if(profile.id===this.state.hostId&&this.hostSuccessionTimer){clearTimeout(this.hostSuccessionTimer);this.hostSuccessionTimer=null;}this.rt.event({code:"PLAYER_RECONNECTED",category:"presence",actorId:profile.id,message:`${profile.name} recuperou/reconectou o perfil salvo.`});this.scheduleSave();return;}if(this.state.locked)throw Error("Sala bloqueada para novos jogadores.");if(this.state.players.size>=this.state.maxPlayers)throw Error("Limite oficial de 6 jogadores.");const p=new Player();p.id=crypto.randomUUID();p.name=text(options.name,24)||"Jogador";p.balance=2_558_000;const recoveryToken=secureToken();p.recoveryTokenHash=hashToken(recoveryToken);const device=text(options.deviceToken,200);p.deviceTokenHash=device?hashToken(device):hashToken(secureToken());this.state.players.set(p.id,p);this.rt.sessionToPlayer.set(client.sessionId,p.id);this.pendingRecoveryBySession.set(client.sessionId,recoveryToken);if(!this.state.hostId)this.state.hostId=p.id;this.rt.event({code:"PLAYER_JOINED",category:"presence",actorId:p.id,message:`${p.name} entrou na sala.`});this.scheduleSave();}
  async onDrop(client:Client){const p=this.rt.playerForSession(client.sessionId);if(p){p.connected=false;this.rt.event({code:"PLAYER_DISCONNECTED",category:"presence",actorId:p.id,message:`${p.name} perdeu a conexão; perfil e estado foram preservados.`});this.scheduleSave();if(p.id===this.state.hostId)this.scheduleHostSuccession();}await this.allowReconnection(client,60);}
  onReconnect(client:Client){const p=this.rt.playerForSession(client.sessionId);if(!p)return;p.connected=true;p.abandoned=false;if(p.id===this.state.hostId&&this.hostSuccessionTimer){clearTimeout(this.hostSuccessionTimer);this.hostSuccessionTimer=null;}this.rt.event({code:"PLAYER_RECONNECTED",category:"presence",actorId:p.id,message:`${p.name} reconectou à sala.`});this.scheduleSave();}
  onLeave(client:Client){const p=this.rt.playerForSession(client.sessionId);this.pendingRecoveryBySession.delete(client.sessionId);if(!p)return;p.connected=false;this.rt.sessionToPlayer.delete(client.sessionId);this.rt.event({code:"PLAYER_DISCONNECTED",category:"presence",actorId:p.id,message:`${p.name} saiu; perfil preservado para recuperação.`});if(p.id===this.state.hostId)this.scheduleHostSuccession();this.scheduleSave();}
  private scheduleHostSuccession(){if(this.hostSuccessionTimer)clearTimeout(this.hostSuccessionTimer);this.hostSuccessionTimer=setTimeout(()=>{const host=this.state.players.get(this.state.hostId);if(host?.connected)return;const next=[...this.state.players.values()].find(p=>p.connected&&!p.bankrupt);if(!next)return;const previous=this.state.hostId;this.state.hostId=next.id;this.rt.event({code:"ADMIN_SUCCESSION",category:"admin",actorId:next.id,targetPlayerId:previous,message:`${next.name} assumiu a administração após ausência prolongada do ADM.`,metadata:{classification:"APP_BEHAVIOR",absenceMs:90_000}});this.broadcast("admin_transferred",{from:this.state.players.get(previous)?.name||"ADM ausente",to:next.name,automatic:true});this.scheduleSave();},90_000);}

  private backup(client:Client){if(!this.rt.requireAdmin(client))return;void this.sendBackup(client);}
  private async sendBackup(client:Client){try{await this.saveNow(true);const backup=sanitizeForExport(serialize(this.state,this.pinHash));client.send("backup",{filename:`BancoMundo-${this.state.saveCode}-v${APP_VERSION}.json`,content:JSON.stringify(backup,null,2)});}catch(error){client.send("error",error instanceof Error?`Falha ao gerar backup: ${error.message}`:"Falha ao gerar backup.");}}

  private report(client:Client){
    const requester=this.rt.me(client);if(!this.state.winnerId&&requester.id!==this.state.hostId){client.send("error","Somente o ADM pode exportar relatório antes do encerramento da partida.");return;}
    const winner=this.state.winnerId?this.state.players.get(this.state.winnerId):undefined;
    const now=Date.now(),endedAt=this.state.gameFinishedAt||now,startedAt=this.state.startedAt||0,durationMs=startedAt?Math.max(0,endedAt-startedAt-this.state.totalPausedMs):0;
    const players=[...this.state.players.values()].map(p=>({id:p.id,name:p.name,bankrupt:p.bankrupt,abandoned:p.abandoned,balance:p.balance,habeasCorpus:p.habeasCorpus,assets:[...p.assets].map(a=>({catalogId:a.catalogId,name:a.name,kind:a.kind,development:a.development,mortgaged:a.mortgaged})),stats:JSON.parse(JSON.stringify(p.stats)),metrics:this.rt.engine.metrics(p.id)}));
    const rules=JSON.parse(JSON.stringify(this.state.rules));
    client.send("report",JSON.stringify({version:APP_VERSION,roomId:this.roomId,saveCode:this.state.saveCode,generatedAt:new Date().toISOString(),startedAt:startedAt?new Date(startedAt).toISOString():null,finishedAt:this.state.gameFinishedAt?new Date(this.state.gameFinishedAt).toISOString():null,durationMs,mode:this.state.mode,rules,houseRules:rules.preset!=="official",winner:winner?{id:winner.id,name:winner.name,metrics:this.rt.engine.metrics(winner.id)}:null,players,result:{gamePhase:this.state.gamePhase,round:this.state.round,turnNumber:this.state.turnNumber,housesRemaining:this.state.housesRemaining},events:[...this.state.events].map(e=>({seq:e.seq,code:e.code,category:e.category,actorId:e.actorId,targetPlayerId:e.targetPlayerId,catalogId:e.catalogId,amount:e.amount,metadata:e.metadata,message:e.message,at:e.at}))},null,2));
  }
  private pauseRoom(client:Client){if(!this.rt.requireAdmin(client))return;if(this.state.paused)return;this.state.paused=true;this.rt.engine.pauseTimer();this.rt.event({code:"ROOM_PAUSED",category:"admin",actorId:this.rt.me(client).id,message:`${this.rt.me(client).name} pausou e salvou a partida.`});void this.saveNow(true);this.broadcast("room_paused",{saveCode:this.state.saveCode,message:"Partida pausada e salva."});}
  private resumeRoom(client:Client){if(!this.rt.requireAdmin(client))return;if(!this.state.paused)return;this.state.paused=false;this.rt.engine.resumeTimer();this.rt.event({code:"ROOM_RESUMED",category:"admin",actorId:this.rt.me(client).id,message:`${this.rt.me(client).name} retomou a partida.`});this.scheduleSave();}
  private endRoom(client:Client){if(!this.rt.requireAdmin(client))return;this.state.ended=true;this.state.locked=true;this.lock();this.state.pending.clear();this.state.trades.clear();this.state.settlements.clear();this.rt.event({code:"ROOM_ENDED",category:"admin",actorId:this.rt.me(client).id,message:`${this.rt.me(client).name} encerrou a sala.`});void this.saveNow(true);this.broadcast("room_ended","A sala foi encerrada pelo ADM.");setTimeout(()=>this.disconnect(4001),700);}
  private scheduleSave(){if(!this.rt.isDirty()||this.persistenceConflict)return;if(this.saveTimer)clearTimeout(this.saveTimer);this.saveTimer=setTimeout(()=>void this.saveNow(),250);}
  private handlePersistenceConflict(reason:string){if(this.persistenceConflict)return;this.persistenceConflict=true;this.state.paused=true;this.state.locked=true;this.lock();this.rt.event({code:"PERSISTENCE_CONFLICT",category:"system",message:"Conflito crítico de persistência detectado. A sala foi pausada para evitar sobrescrita de estado.",metadata:{reason}});this.rt.takeDirty();this.broadcast("persistence_conflict",{reason,message:"Sala pausada por conflito de persistência. Recarregue a revisão mais recente com segurança."});}
  private async saveNow(force=false){if(this.persistenceConflict)return;if(!force&&!this.rt.isDirty())return;const wasDirty=this.rt.takeDirty();if(!wasDirty&&!force)return;this.saveChain=this.saveChain.then(async()=>{try{await atomicSave(this.state,this.pinHash);}catch(e){if(e instanceof SaveConflictError){this.handlePersistenceConflict(e.code);return;}this.rt.markDirty();console.error("Falha ao salvar",e);}});await this.saveChain;}
  async onDispose(){if(this.hostSuccessionTimer)clearTimeout(this.hostSuccessionTimer);if(this.rt?.isDirty()&&!this.persistenceConflict)await this.saveNow(true);await releaseRoomLease(this.state?.saveCode||"");}
}
